const taxonomy1 = [
  'Agri-environmental science	Agricultural systems',
  'Agri-environmental science	Crop protection',
  'Agri-environmental science	Crop science',
  'Agri-environmental science	Earth & environmental',
  'Agri-environmental science	Soil science',
  'Animal science	3Rs',
  'Animal science	Animal & human physiology',
  'Animal science	Animal behaviour',
  'Animal science	Animal diseases',
  'Animal science	Animal organisms',
  'Animal science	Animal reproduction',
  'Animal science	Animal welfare',
  'Animal science	Endocrinology',
  'Animal science	Immunology',
  'Animal science	Livestock production',
  'Animal science	Musculoskeletal system',
  'Animal science	Parasitology',
  'Animal science	Systems neuroscience',
  'Animal science	Psychology',
  'Archaeology	Archaeological Theory',
  'Archaeology	Archaeology Of Human Origins',
  'Archaeology	Archaeology of Literate Soc.',
  'Archaeology	Landscape & Environ. Archaeol.',
  'Archaeology	Palaeobiology',
  'Archaeology	Prehistoric Archaeology',
  'Archaeology	Science-Based Archaeology',
  'Archaeology	Quaternary Science',
  'Archaeology	Maritime Archaeology',
  'Archaeology	Industrial Archaeology',
  'Area Studies	African Studies',
  'Area Studies	American Studies',
  'Area Studies	Hispanic & Latin American Stud',
  'Area Studies	Asian & Middle Eastern Studies',
  'Area Studies	European Studies',
  'Area Studies	Pacific Studies',
  'Area Studies	Oceanic Studies',
  'Astronomy - observation	Astron. & Space Sci. Technol.',
  'Astronomy - observation	Data Handling & Storage',
  'Astronomy - observation	Extra-Galactic Astron.&Cosmol.',
  'Astronomy - observation	Galactic & Interstellar Astron',
  'Astronomy - observation	Part. Phys/Astron. Instrument.',
  'Astronomy - observation	Stellar Astronomy',
  'Astronomy - theory	Computational Methods & Tools',
  'Atmospheric phys. & chemistry	Atmospheric Kinetics',
  'Atmospheric phys. & chemistry	Boundary Layer Meteorology',
  'Atmospheric phys. & chemistry	Large Scale Dynamics/Transport',
  'Atmospheric phys. & chemistry	Radiative Processes & Effects',
  'Atmospheric phys. & chemistry	Stratospheric Processes',
  'Atmospheric phys. & chemistry	Tropospheric Processes',
  'Atmospheric phys. & chemistry	Upper Atmos Process & Geospace',
  'Atmospheric phys. & chemistry	Water In The Atmosphere',
  'Atmospheric phys. & chemistry	Ocean - Atmosphere Interact.',
  'Atmospheric phys. & chemistry	Land - Atmosphere Interactions',
  'Atomic & molecular physics	Atoms & Ions',
  'Atomic & molecular physics	Cold Atomic Species',
  'Atomic & molecular physics	Light-Matter Interactions',
  'Atomic & molecular physics	Scattering & Spectroscopy',
  'Atomic & molecular physics	Fusion',
  'Bioengineering	Biochemical engineering',
  'Bioengineering	Bionanoscience',
  'Bioengineering	Bioreactors',
  'Bioengineering	Environmental biotechnology',
  'Bioengineering	Macro-molecular delivery',
  'Bioengineering	Metabolic engineering',
  'Bioengineering	Novel industrial products',
  'Bioengineering	Protein engineering',
  'Bioengineering	Tissue engineering',
  'Bioengineering	Bioenergy',
  'Bioengineering	Biomaterials',
  'Biomolecules & biochemistry	Biochemistry & physiology',
  'Biomolecules & biochemistry	Bioenergetics',
  'Biomolecules & biochemistry	Biological membranes',
  'Biomolecules & biochemistry	Carbohydrate Chemistry',
  'Biomolecules & biochemistry	Catalysis & enzymology',
  'Biomolecules & biochemistry	Chemical Biology',
  'Biomolecules & biochemistry	Multiprotein complexes',
  'Biomolecules & biochemistry	Protein chemistry',
  'Biomolecules & biochemistry	Protein expression',
  'Biomolecules & biochemistry	Protein folding / misfolding',
  'Biomolecules & biochemistry	Structural biology',
  'Biomolecules & biochemistry	Ageing: chemistry/biochemistry',
  'Biomolecules & biochemistry	Biophysics',
  'Catalysis & surfaces	Catalysis & Applied Catalysis',
  'Catalysis & surfaces	Electrochemical Science & Eng.',
  'Catalysis & surfaces	Surfaces & Interfaces',
  'Catalysis & surfaces	Complex fluids & soft solids',
  'Cell biology	Cell cycle',
  'Cell biology	Cells',
  'Cell biology	Communication & signalling',
  'Cell biology	Organelles & components',
  'Cell biology	Receptors',
  'Cell biology	Stem cell biology',
  'Chem. React. Dyn. & mechanisms	Gas & Solution Phase Reactions',
  'Chem. React. Dyn. & mechanisms	Physical Organic Chemistry',
  'Chemical measurement	Analytical Science',
  'Chemical measurement	Chemical Structure',
  'Chemical measurement	Instrumentation Eng. & Dev.',
  'Chemical synthesis	Asymmetric Chemistry',
  'Chemical synthesis	Biological & Medicinal Chem.',
  'Chemical synthesis	Chemical Synthetic Methodology',
  'Chemical synthesis	Combinatorial Chemistry',
  'Chemical synthesis	Co-ordination Chemistry',
  'Chemical synthesis	Synthetic biology',
  'Chemical synthesis	Drug Formulation & Delivery',
  'Civil eng. & built environment	Building Ops & Management',
  'Civil eng. & built environment	Civil Engineering Materials',
  'Civil eng. & built environment	Construction Ops & Management',
  'Civil eng. & built environment	Ground Engineering',
  'Civil eng. & built environment	Mining & Minerals Extraction',
  'Civil eng. & built environment	Pavement Engineering',
  'Civil eng. & built environment	Structural Engineering',
  'Civil eng. & built environment	Transport Ops & Management',
  'Civil eng. & built environment	Urban & Land Management',
  'Civil eng. & built environment	Water Engineering',
  'Civil eng. & built environment	Coastal & Waterway Engineering',
  'Civil eng. & built environment	Waste Management',
  'Civil eng. & built environment	Earth Engineering',
  'Civil eng. & built environment	Materials testing & eng.',
  'Civil eng. & built environment	Oil & Gas Extraction',
  'Classics	Classical Literature',
  'Classics	Classical Reception',
  'Classics	Languages & Linguistics',
  'Classics	Epigraphy & Papyrology',
  'Classics	Philosophy, Thought & Religion',
  'Climate & climate change	Climate & Climate Change',
  'Climate & climate change	Regional & Extreme Weather',
  'Climate & climate change	Palaeoenvironments',
  'Complexity science	Complexity Science',
  'Cultural & museum studies	Conservation Of Art & Textiles',
  'Cultural & museum studies	Conservation Science',
  'Cultural & museum studies	Cultural Geography',
  'Cultural & museum studies	Cultural Studies & Pop Culture',
  'Cultural & museum studies	Gender & Sexuality Studies',
  'Cultural & museum studies	Heritage Management',
  'Cultural & museum studies	Museum & Gallery Studies',
  'Cultural & museum studies	Policy, Arts Mgmt & Creat Ind',
  'Dance	Choreography',
  'Dance	Dance Notation',
  'Dance	Dance Performance',
  'Dance	History Of Dance',
  'Dance	Social Dance',
  'Demography	Demography (General)',
  'Demography	Reproductive and sexual health',
  'Demography & human geography	Demography',
  'Demography & human geography	Human Geography',
  'Design	Architecture HTP',
  'Design	Design Engineering',
  'Design	Design Processes',
  'Design	Digital Art & Design',
  'Design	Product Design',
  'Design	Design HTP',
  'Development studies	Area & Development Studies',
  'Development studies	Pol.,International Rel.&Dev.',
  'Development studies	Economic Development',
  'Development studies	Development Studies',
  'Development studies	Sociology and Development',
  'Development studies	Nat Resources, Env & Rural Dev',
  'Development studies	Anthropology and Development',
  'Development studies	Social policy and Development',
  'Development studies	Global Health and Medicine',
  'Development studies	Internat Education and Dev',
  'Development studies	Law, Democracy and Development',
  'Development studies	Demography and Development',
  'Development studies	Dev Informatics & Technology',
  'Development studies	Geography and Development',
  'Development studies	Management & Bus Studies & Dev',
  'Development studies	Regional Development',
  'Drama & theatre studies	Drama & Theatre - Other',
  'Drama & theatre studies	Dramaturgy',
  'Drama & theatre studies	Performance & Live Art',
  'Drama & theatre studies	Scenography',
  'Drama & theatre studies	Theatre & History',
  'Drama & theatre studies	Theatre & Society',
  'Drama & theatre studies	Theories Of Theatre',
  'Ecol, biodivers. & systematics	Behavioural Ecology',
  'Ecol, biodivers. & systematics	Community Ecology',
  'Ecol, biodivers. & systematics	Conservation Ecology',
  'Ecol, biodivers. & systematics	Population Ecology',
  'Ecol, biodivers. & systematics	Systematics & Taxonomy',
  'Economics	Economics (General)',
  'Economics	Development economics',
  'Economics	Econometrics',
  'Economics	Financial economics',
  'Economics	Industrial Organisation (R&D)',
  'Economics	International economics',
  'Economics	Macroeconomics',
  'Economics	Labour economics',
  'Economics	Public economics',
  'Economics	Microeconomic theory',
  'Economics	Law and economics',
  'Economics	Behavioural & experimental eco',
  'Economics	Environmental economics',
  'Education	Education (General)',
  'Education	Sociology of Education',
  'Education	Psychology of Education',
  'Education	Curriculum areas',
  'Education	Elements of Education',
  'Education	Phases of education',
  'Education	Education Policy',
  'Education	ICT and education',
  'Electrical engineering	Bioelectronic Devices',
  'Electrical engineering	Electric Motor & Drive Systems',
  'Electrical engineering	Power Electronics',
  'Electrical engineering	Power Sys Man, Prot & Control',
  'Electrical engineering	Power Systems Plant',
  'Electrical engineering	Robotics & Autonomy',
  'Electrical engineering	Optical Devices & Subsystems',
  'Electrical engineering	Optoelect. Devices & Circuits',
  'Energy	Carbon Capture & Storage',
  'Energy	Coal Technology',
  'Energy	Energy - Conventional',
  'Energy	Energy - Marine & Hydropower',
  'Energy	Energy - Nuclear',
  'Energy	Energy Efficiency',
  'Energy	Energy Storage',
  'Energy	Fuel Cell Technologies',
  'Energy	Solar Technology',
  'Energy	Sustainable Energy Networks',
  'Energy	Sustainable Energy Vectors',
  'Energy	Wind Power',
  'Environmental engineering	Assess/Remediate Contamination',
  'Environmental engineering	Waste Minimisation',
  'Environmental planning	Env Planning (General)',
  'Environmental planning	Spatial Planning',
  'Environmental planning	Urban Design',
  'Environmental planning	Landscape  Architecture',
  'Facility Development	Accelerator R&D',
  'Facility Development	Central Laser Facility',
  'Facility Development	Diamond Light Source',
  'Facility Development	ESRF',
  'Facility Development	ILL',
  'Facility Development	ISIS T1',
  'Facility Development	ISIS T2',
  'Facility Development	Research complex at Harwell',
  'Facility Development	X-FEL',
  'Food science & nutrition	Diet & health',
  'Food science & nutrition	Food microbiology',
  'Food science & nutrition	Food processing',
  'Food science & nutrition	Food structure/composition',
  'Genetics & development	Animal developmental biology',
  'Genetics & development	Epigenetics',
  'Genetics & development	Evolution & populations',
  'Genetics & development	Gene action & regulation',
  'Genetics & development	Gene therapy',
  'Genetics & development	Genome organisation',
  'Genetics & development	Microbial',
  'Genetics & development	Population Genetics/Evolution',
  'Genetics & development	Recombination',
  'Geosciences	Geohazards',
  'Geosciences	Glacial & Cryospheric Systems',
  'Geosciences	Hydrogeology',
  'Geosciences	Hydrological Processes',
  'Geosciences	Mantle & Core Processes',
  'Geosciences	Properties Of Earth Materials',
  'Geosciences	Sediment/Sedimentary Processes',
  'Geosciences	Tectonic Processes',
  'Geosciences	Volcanic Processes',
  'Geosciences	Earth Resources',
  'History	Cultural History',
  'History	Economic & Soc Hist (General)',
  'History	History of Sci./Med./Technol.',
  'History	Imperial/Colonial History',
  'History	Industrial History',
  'History	Maritime History',
  'History	Political History',
  'History	Post-Colonial Studies',
  'History	Religious History',
  'History	War Studies',
  'Human Geography	Human Geography (General)',
  'Human Geography	Demography/Pop Geography',
  'Human Geography	Cultural and Anthrop Geography',
  'Human Geography	Social Geography',
  'Human Geography	Economic Geography',
  'Human Geography	Political Geography',
  'Human Geography	Historical Geography',
  'Human Geography	Environmental Geography',
  'Human Geography	Development Geography',
  'Human Geography	Urban Geography',
  'Human Geography	Rural Geography',
  'Human Geography	Recreation/Tourism Geography',
  'Human Geography	Transport Geography',
  'Human Geography	Regional Geography',
  'Human Geography	Cartography and GIS',
  'Info. & commun. Technol.	Artificial Intelligence',
  'Info. & commun. Technol.	Cognitive Science Appl. in ICT',
  'Info. & commun. Technol.	Computer Graphics & Visual.',
  'Info. & commun. Technol.	Digital Signal Processing',
  'Info. & commun. Technol.	Displays',
  'Info. & commun. Technol.	Electronic Devices & Subsys.',
  'Info. & commun. Technol.	Fundamentals of Computing',
  'Info. & commun. Technol.	Human Communication in ICT',
  'Info. & commun. Technol.	Human-Computer Interactions',
  'Info. & commun. Technol.	Networks & Distributed Systems',
  'Info. & commun. Technol.	Image & Vision Computing',
  'Info. & commun. Technol.	Information & Knowledge Mgmt',
  'Info. & commun. Technol.	Microsystems',
  'Info. & commun. Technol.	Mobile Computing',
  'Info. & commun. Technol.	Modelling & simul. of IT sys.',
  'Info. & commun. Technol.	Multimedia',
  'Info. & commun. Technol.	Music & Acoustic Technology',
  'Info. & commun. Technol.	New & Emerging Comp. Paradigms',
  'Info. & commun. Technol.	Optical Communications',
  'Info. & commun. Technol.	Parallel Computing',
  'Info. & commun. Technol.	RF & Microwave Technology',
  'Info. & commun. Technol.	Software Engineering',
  'Info. & commun. Technol.	System on Chip',
  'Info. & commun. Technol.	Vision & Senses - ICT appl.',
  'Info. & commun. Technol.	VLSI Design',
  'Info. & commun. Technol.	Computer Sys. & Architecture',
  'Instrument. sensor & detectors	Exploration Technology',
  'Instrument. sensor & detectors	Survey & Monitoring',
  'Languages & Literature	Middle East & African Studies',
  'Languages & Literature	Asiatic & Oriental Studies',
  'Languages & Literature	Australasian Studies',
  'Languages & Literature	Celtic Studies',
  'Languages & Literature	Comparative Literature',
  'Languages & Literature	Comparative Studies',
  'Languages & Literature	Creative Writing',
  'Languages & Literature	English Language & Literature',
  'Languages & Literature	Ethnography & Anthropology',
  'Languages & Literature	French Studies',
  'Languages & Literature	German, inc. Dutch & Yiddish',
  'Languages & Literature	Hispanic, Portguese & Latin',
  'Languages & Literature	History & Dev. of English Lang',
  'Languages & Literature	Interpreting & Translation',
  'Languages & Literature	Italian Studies',
  'Languages & Literature	Language Training/Educational',
  'Languages & Literature	Lifewriting',
  'Languages & Literature	Literary & Cultural Theory',
  'Languages & Literature	Medieval Literature',
  'Languages & Literature	Russian, Slavonic & E European',
  'Languages & Literature	Scandinavian Studies',
  'Languages & Literature	Gender & Sexuality',
  'Law & legal studies	Common Law inc. Commercial Law',
  'Law & legal studies	Comparative Law',
  'Law & legal studies	Criminal Law & Criminology',
  'Law & legal studies	EU Law',
  'Law & legal studies	Human Rights',
  'Law & legal studies	International Law',
  'Law & legal studies	Jurisprudence/Legal Philosophy',
  'Law & legal studies	Law Regulated By Statute',
  'Law & legal studies	Law Relating To Property',
  'Law & legal studies	Legal History',
  'Law & legal studies	Public Law',
  'Law & legal studies	Socio Legal Studies',
  'Library & information studies	Archives',
  'Library & information studies	Computational Studies',
  'Library & information studies	Information Sci. & Retrieval',
  'Library & information studies	Library Studies',
  'Library & information studies	Records Management',
  'Linguistics	Language Acquisition',
  'Linguistics	Language Variation & Change',
  'Linguistics	Applied Linguistics',
  'Linguistics	Comput./Corpus Linguistics',
  'Linguistics	Lexicon',
  'Linguistics	Linguistic Theory',
  'Linguistics	Morphology & Phonology',
  'Linguistics	Phonetics',
  'Linguistics	Psycholinguistics',
  'Linguistics	Semantics & Pragmatics',
  'Linguistics	Sociolinguistics',
  'Linguistics	Syntax',
  'Linguistics	Textual Editing & Bibliography',
  'Linguistics	Linguistics (General)',
  'Linguistics	Computational Linguistics',
  'Linguistics	Corpus Linguistics',
  'Management & business studies	Manage & Bus Stud (General)',
  'Management & business studies	Manufact. Business Strategy',
  'Management & business studies	Manufact. Enterprise Ops& Mgmt',
  'Management & business studies	Strategic Management',
  'Management & business studies	Project Studies',
  'Management & business studies	Entrepreneurship',
  'Management & business studies	Leadership',
  'Management & business studies	Employment Studies',
  'Management & business studies	Human Resource Management',
  'Management & business studies	Innovation',
  'Management & business studies	Marketing',
  'Management & business studies	Operations Management',
  'Management & business studies	Hosp, Leisure & tourism manage',
  'Management & business studies	Governance',
  'Management & business studies	Sustainability Management',
  'Management & business studies	Knowledge Management',
  'Management & business studies	Retail Management',
  'Management & business studies	Public Administration',
  'Management & business studies	Organisational Studies',
  'Management & business studies	International Business',
  'Management & business studies	Finance and Accounting',
  'Manufacturing	Manufacturing Machine & Plant',
  'Manufacturing	Design & Testing Technology',
  'Marine environments	Ecosystem Scale Processes',
  'Marine environments	Land - Ocean Interactions',
  'Marine environments	Ocean Circulation',
  'Marine environments	Biogeochemical Cycles',
  'Materials processing	Materials Processing',
  'Materials processing	Particle Technology',
  'Materials sciences	Materials Characterisation',
  'Materials sciences	Materials Synthesis & Growth',
  'Mathematical sciences	Algebra & Geometry',
  'Mathematical sciences	Continuum Mechanics',
  'Mathematical sciences	Logic & Combinatorics',
  'Mathematical sciences	Mathematical Analysis',
  'Mathematical sciences	Mathematical Aspects of OR',
  'Mathematical sciences	Mathematical Physics',
  'Mathematical sciences	Non-linear Systems Mathematics',
  'Mathematical sciences	Numerical Analysis',
  'Mathematical sciences	Statistics & Appl. Probability',
  'Mechanical engineering	Acoustics',
  'Mechanical engineering	Aerodynamics',
  'Mechanical engineering	Combustion',
  'Mechanical engineering	Eng. Dynamics & Tribology',
  'Mechanical engineering	Mech. & Fluid Power Transmiss.',
  'Mechanical engineering	Underwater Engineering',
  'Mechanical engineering	Heat & Mass Transfer',
  'Media	Journalism',
  'Media	Media & Communication Studies',
  'Media	New Media/Web-Based Studies',
  'Media	Publishing',
  'Media	Television HTC',
  'Media	Film History, T & C',
  'Medical & health interface	Biomechanics & Rehabilitation',
  'Medical & health interface	Biomedical neuroscience',
  'Medical & health interface	Biomedical sciences',
  'Medical & health interface	Environment & Health',
  'Medical & health interface	Med.Instrument.Device& Equip.',
  'Medical & health interface	Medical science & disease',
  'Medical & health interface	Mental Health',
  'Medical & health interface	Tissue Engineering',
  'Microbial sciences	Extremophiles',
  'Microbial sciences	Microbiology',
  'Microbial sciences	Microorganisms',
  'Microbial sciences	Responses to environment',
  'Microbial sciences	Environmental Microbiology',
  'Music	Classical Music',
  'Music	Composition',
  'Music	History Of Music',
  'Music	Music & Society',
  'Music	Musical Performance',
  'Music	Musicology',
  'Music	Popular Music',
  'Music	Traditional Music',
  'Nuclear physics	Hadron Physics',
  'Nuclear physics	Nuclear Astrophysics',
  'Nuclear physics	Nuclear Structure',
  'Nuclear physics	Relativistic Heavy Ions',
  'Omic sciences & technologies	Environmental Genomics',
  'Omic sciences & technologies	Functional genomics',
  'Omic sciences & technologies	Genomics',
  'Omic sciences & technologies	Glycomics',
  'Omic sciences & technologies	Metabolomics / Metabonomics',
  'Omic sciences & technologies	Proteomics',
  'Omic sciences & technologies	Transcriptomics',
  'Optics, photonics & lasers	Lasers & Optics',
  'Optics, photonics & lasers	Optical Phenomena',
  'Optics, photonics & lasers	Quantum Optics & Information',
  'Particle astrophysics	Cosmic Microwave Background',
  'Particle astrophysics	Cosmology',
  'Particle astrophysics	Direct Dark Matter Detection',
  'Particle astrophysics	Gamma Ray Astronomy',
  'Particle astrophysics	Gravitational Waves',
  'Particle astrophysics	High Energy Cosmic Rays',
  'Particle physics - experiment	B Physics/Flavour Physics',
  'Particle physics - experiment	Beyond The Standard Model',
  'Particle physics - experiment	Dark Energy',
  'Particle physics - experiment	Neutrino Physics',
  'Particle physics - theory	Lattice QCD',
  'Particle physics - theory	Phenomenology',
  'Particle physics - theory	Quantum Field Theory',
  'Particle physics - theory	String Theory',
  'Particle physics - theory	The Standard Model',
  'Philosophy	Aesthetics',
  'Philosophy	Epistemology',
  'Philosophy	Ethics',
  'Philosophy	History Of Ideas',
  'Philosophy	History Of Philosophy',
  'Philosophy	Language & Philosophical Logic',
  'Philosophy	Metaphysics',
  'Philosophy	Philosophy Of Mind',
  'Philosophy	Philosophy Of Religion',
  'Philosophy	Science & Maths, & Math Logic',
  'Philosophy	Political Philosophy',
  'Planetary science	Extra Solar Planets',
  'Planetary science	Non-Terrestrial Planetary Sci.',
  'Planetary science	Planetary Atmospheres',
  'Planetary science	Planetary Surfaces & Geology',
  'Planetary science	Solar Bodies',
  'Plant & crop science	Environmental Physiology',
  'Plant & crop science	Interaction with organisms',
  'Plant & crop science	Plant cell biology',
  'Plant & crop science	Plant developmental biology',
  'Plant & crop science	Plant organisms',
  'Plant & crop science	Plant physiology',
  'Plant & crop science	Plant reproductive biology',
  'Plant & crop science	Plant responses to environment',
  'Plasma physics	Plasmas - Laser & Fusion',
  'Plasma physics	Plasmas - Technological',
  'Pol. sci. & internat. studies	Diplomacy & Internat Relations',
  'Pol. sci. & internat. studies	Internat. Studies & Relations',
  'Pol. sci. & internat. studies	Political Science',
  'Pol. sci. & internat. studies	Politics',
  'Pol. sci. & internat. studies	International Organisations',
  'Pol. sci. & internat. studies	International Relations Theory',
  'Pol. sci. & internat. studies	Peace Studies',
  'Pol. sci. & internat. studies	Conflict/War Studies',
  'Pol. sci. & internat. studies	Security Studies',
  'Pol. sci. & internat. studies	Internat Political Economy',
  'Pol. sci. & internat. studies	Foreign Policy Studies',
  'Pol. sci. & internat. studies	Elections/Electoral studies',
  'Pol. sci. & internat. studies	Middle East Studies',
  'Pol. sci. & internat. studies	European/EU Studies',
  'Pollution, waste & resources	Ecotoxicology',
  'Pollution, waste & resources	Pollution',
  'Process engineering	Bioprocess Engineering',
  'Process engineering	Design of Process systems',
  'Process engineering	Fluid Dynamics',
  'Process engineering	Multiphase Flow',
  'Process engineering	Reactor Engineering',
  'Process engineering	Rheology',
  'Process engineering	Safety & Reliability of Plant',
  'Process engineering	Separation Processes',
  'Psychology	Psychology (General)',
  'Psychology	Biological Psychology',
  'Psychology	Child Psychology',
  'Psychology	Cognitive Psychology',
  'Psychology	Developmental Psychology',
  'Psychology	Education and School',
  'Psychology	Experimental Psychology',
  'Psychology	Forensic Psychology',
  'Psychology	Health Psychology',
  'Psychology	Industrial-Org/Occupational',
  'Psychology	Social Psychology',
  'Psychology	Sport and Exercise',
  'Psychology	Mathematical & Statistic Psych',
  'Psychology	Gerontology',
  'Science and Technology Studies	Science & Technology Studies',
  'Science and Technology Studies	Science and Technology Studies',
  'Social anthropology	Social Anthropology (General)',
  'Social anthropology	Econ, Pol & Env Anthropology',
  'Social anthropology	Kinship Health & relatedness',
  'Social anthropology	Rel, Material & Cog Anthrop',
  'Social anthropology	Anthropological Methodology',
  'Social policy	Social Policy (General)',
  'Social work	Social Work (General)',
  'Social work	Children and Families',
  'Social work	Social Work with Adults',
  'Social work	International Social Work',
  'Sociology	Sociology (General)',
  'Sociology	Criminology',
  'Sociology	Cultural Studies',
  'Sociology	Economic Sociology',
  'Sociology	Edu Sociocloy/Sociology of Edu',
  'Sociology	Ethnicity',
  'Sociology	Environment',
  'Sociology	Globalism and Development',
  'Sociology	Media Studies',
  'Sociology	Med Soc/Soc Health & Illness',
  'Sociology	Political Sociology',
  'Sociology	Sociology of Religion',
  'Sociology	Social Theory',
  'Sociology	Stratification',
  'Sociology	Urbanisation',
  'Sociology	Womens and Gender Studies',
  'Solar & terrestrial physics	Solar & Solar-Terrestrial Phys',
  'Solar & terrestrial physics	Solar Studies',
  'Supercond, magn. &quant.fluids	Condensed Matter Physics',
  'Supercond, magn. &quant.fluids	Electromagnetics',
  'Supercond, magn. &quant.fluids	Magnetism/Magnetic Phenomena',
  'Supercond, magn. &quant.fluids	Quantum Fluids & Solids',
  'Systems engineering	Control Engineering',
  'Systems engineering	Intelligent & Expert Systems',
  'Systems engineering	Intelligent Measurement Sys.',
  'Terrest. & freshwater environ.	Earth Surface Processes',
  'Terrest. & freshwater environ.	Water Quality',
  'Theology, divinity & religion	Alternative Spiritualities',
  'Theology, divinity & religion	Atheism/Secularism',
  'Theology, divinity & religion	Buddhism',
  'Theology, divinity & religion	History of Church & Theology',
  'Theology, divinity & religion	Contemporary Religion',
  'Theology, divinity & religion	East Asian Religions',
  'Theology, divinity & religion	Hinduism',
  'Theology, divinity & religion	Inter-faith Relations',
  'Theology, divinity & religion	Islam',
  'Theology, divinity & religion	Jainism',
  'Theology, divinity & religion	Judaism',
  'Theology, divinity & religion	Liturgy',
  'Theology, divinity & religion	Modern Theology',
  'Theology, divinity & religion	New Testament',
  'Theology, divinity & religion	Old Testament',
  'Theology, divinity & religion	Sikhism',
  'Theology, divinity & religion	Systematic Theology',
  'Tools, technologies & methods	Bioinformatics',
  'Tools, technologies & methods	Bionanotechnology',
  'Tools, technologies & methods	Development (Biosciences)',
  'Tools, technologies & methods	Environmental Informatics',
  'Tools, technologies & methods	eScience',
  'Tools, technologies & methods	High Performance Computing',
  'Tools, technologies & methods	Medical Imaging',
  'Tools, technologies & methods	Research approaches',
  'Tools, technologies & methods	Social Stats., Comp. & Methods',
  'Tools, technologies & methods	Technol. for Environ. Appl.',
  'Tools, technologies & methods	Theoretical biology',
  'Tools, technologies & methods	Tools for the biosciences',
  'Tools, technologies & methods	Remote Sensing & Earth Obs.',
  'Tools, technologies & methods	Technology and method dev',
  'Visual arts	Applied Arts HTP',
  'Visual arts	Art History',
  'Visual arts	Art Theory & Aesthetics',
  'Visual arts	Digital Arts HTP',
  'Visual arts	Fine Art HTP',
  'Visual arts	Installation & Sound Art HTP',
  'Visual arts	Photography HTP',
  'Visual arts	Time-Based Media HTP',
  'Visual arts	Film-based media (H, T & P)',
  'Visual arts	Community Art inc A & H',
];

export const concatTaxonomy1 = taxonomy1;
