let reportingData = [
  'EUC11 EU Classifications (COFUND_EJP) European Joint Programme Cofund',
  'EUC10 EU Classifications (CS) Clean Sky',
  'EUC12 EU Classifications (EDCTP) European & Developing Countries Clinical Trials Partnership',
  'EUC13 EU Classifications (EMPIR) European Metrology Programme for Innovation and Research',
  'EUC16 EU Classifications (IA) Innovation Action',
  'EUC17 EU Classifications (IPr) Inducement Prize',
  'EUC18 EU Classifications (ISIB) Innovative, Sustainable & Inclusive Bio-economy',
  'EUC19 EU Classifications (JTI) Joint Technology Initiatives',
  'EUC20 EU Classifications (KICS) Knowledge and Innovation Communities',
  'EUC21 EU Classifications (PCP) Pre-Commercial Procurement',
  'EUC22 EU Classifications (RPr) Recognition Prize',
  'EUC23 EU Classifications (SFS) Sustainable Food Security',
  '3PTY  3rd Party Involvement',
  'JACSX350 Academic studies in Education Academic studies in Adult Education',
  'JACSX300 Education Academic studies in Education',
  'JACSX370 Academic studies in Education Academic studies in Education (across phases)',
  'JACSX390 Academic studies in Education Academic studies in Education not elsewhere classified',
  'JACSX341 Academic studies in Tertiary Education Academic studies in Further Education',
  'JACSX342 Academic studies in Tertiary Education Academic studies in Higher Education',
  'JACSX310 Academic studies in Education Academic studies in Nursery Education',
  'JACSX320 Academic studies in Education Academic studies in Primary Education',
  'JACSX330 Academic studies in Education Academic studies in Secondary Education',
  'JACSX360 Academic studies in Education Academic studies in Specialist Education',
  'JACSX340 Academic studies in Education Academic studies in Tertiary Education',
  'JACSN410 Accounting Accountancy',
  'JACSN400 Business and Administrative studies Accounting',
  'JACSN420 Accounting Accounting Theory',
  'JACSN490 Accounting Accounting not elsewhere classified',
  'JACSF380 Physics Acoustics',
  'JACSH341 Acoustics and Vibration Acoustics',
  'JACSH340 Mechanical Engineering Acoustics and Vibration',
  'JACSW410 Drama Acting',
  'JACSN323 Investment and Insurance Actuarial Science',
  'JACSB343 Alternative Medicine Acupuncture',
  'JACSB740 Nursing Adult Nursing',
  'JACSN561 Promotion and Advertising Advertising',
  'JACSH440 Aerospace Engineering Aerodynamics',
  'JACSH410 Aerospace Engineering Aeronautical Engineering',
  'JACSH400 Engineering Aerospace Engineering',
  'JACSH490 Aerospace Engineering Aerospace Engineering not elsewhere classified',
  'GCA1 GCRF Challenge Areas Affordable, reliable, sustainable energy',
  'JACSV250 History by area African History',
  'JACST510 African studies African Language studies',
  'JACST520 African studies African Literature studies',
  'JACST530 African studies African Society and Culture studies',
  'JACST500 Eastern, Asiatic, African, American and Australasian Languages, Literature and related subjects African studies',
  'JACST590 African studies African studies not elsewhere classified',
  'CSES0000300001 RCUK Programmes Ageing: Long life and Wellbeing',
  'JACSD721 Agricultural Chemistry Agricultural Biochemistry',
  'JACSD710 Agricultural Sciences Agricultural Biology',
  'JACSD730 Agricultural Sciences Agricultural Botany',
  'JACSD720 Agricultural Sciences Agricultural Chemistry',
  'JACSL112 Applied Economics Agricultural Economics',
  'JACSL727 Human and Social Geography by topic Agricultural Geography',
  'JACSD472 Agricultural Technology Agricultural Irrigation and Drainage',
  'JACSD471 Agricultural Technology Agricultural Machinery',
  'JACSD711 Agricultural Sciences Agricultural Microbiology',
  'JACSD411 Arable and Fruit Farming Agricultural Pests and Diseases',
  'JACSD700 Veterinary Sciences, Agriculture and related subjects Agricultural Sciences',
  'JACSD790 Agricultural Sciences Agricultural Sciences not elsewhere classified',
  'JACSD470 Agriculture Agricultural Technology',
  'JACSD740 Agricultural Sciences Agricultural Zoology',
  'NABS108 Reporting - NABS Agriculture',
  'JACSD400 Veterinary Sciences, Agriculture and related subjects Agriculture',
  'JACSD490 Agriculture Agriculture not elsewhere classified',
  'JACSN853 Transport Studies Air Travel',
  'JACSH413 Aeronautical Engineering Air-Combat Engineering',
  'JACSH412 Aeronautical Engineering Air-Freight Transport Engineering',
  'JACSH411 Aeronautical Engineering Air-Passenger Transport Engineering',
  'JACSQ430 Ancient Language studies Akkadian',
  '3PTY0000100002 TSB Aligned',
  'JACSB340 Complementary Medicine Alternative Medicine',
  'JACSD417 Arable and Fruit Farming Amenity Plant Production',
  'JACSV230 History by area American History',
  'JACST710 American studies American Language studies',
  'JACST720 American studies American Literature studies',
  'JACST730 American studies American Society and Culture studies',
  'JACST700 Eastern, Asiatic, African, American and Australasian Languages, Literature and related subjects American studies',
  'JACST790 American studies American studies not elsewhere classified',
  'JACSH652 Systems Engineering Analogue Circuit Engineering',
  'JACSF180 Chemistry Analytical Chemistry',
  'JACSL218 Political Theories Anarchism',
  'JACSB110 Anatomy, Physiology and Pathology Anatomy',
  'JACSB100 Subjects allied to Medicine Anatomy, Physiology and Pathology',
  'JACSB190 Subjects allied to Medicine Anatomy, Physiology and Pathology not elsewhere classified',
  'JACSQ510 Celtic studies Ancient Celtic studies',
  'JACSQ410 Ancient Language studies Ancient Egyptian',
  'JACSV110 History by period Ancient History',
  'JACSQ400 Linguistics, Classics and related subjects Ancient Language studies',
  'JACSQ490 Ancient Language studies Ancient Language studies not elsewhere classified',
  'JACSD321 Animal Health Animal Anatomy',
  'JACSD320 Animal Science Animal Health',
  'JACSD327 Animal Health Animal Nutrition',
  'JACSD323 Animal Health Animal Pathology',
  'JACSD324 Animal Health Animal Pharmacology',
  'JACSD326 Animal Health Animal Pharmacy',
  'JACSD322 Animal Health Animal Physiology',
  'JACSD300 Veterinary Sciences, Agriculture and related subjects Animal Science',
  'JACSD325 Animal Health Animal Toxicology',
  'JACSD328 Animal Health Animal Welfare',
  'JACSW615 Moving Image Techniques Animation Techniques',
  'JACSL600 Social studies Anthropology',
  'JACSL690 Anthropology Anthropology not elsewhere classified',
  'FRAS4 Reporting - FRASCATI Applied - specific',
  'FRAS3 Reporting - FRASCATI Applied - strategic',
  'JACSC910 Others in Biological Sciences Applied Biological Sciences',
  'JACSC110 Biology Applied Biology',
  'JACSC210 Botany Applied Botany',
  'JACSC131 Cell Biology Applied Cell Biology',
  'JACSF110 Chemistry Applied Chemistry',
  'JACSL110 Economics Applied Economics',
  'JACSF851 Environmental Sciences Applied Environmental Sciences',
  'JACSC410 Genetics Applied Genetics',
  'JACSF610 Geology Applied Geology',
  'JACSQ110 Linguistics Applied Linguistics',
  'JACSG120 Mathematics Applied Mathematics',
  'JACSJ210 Metallurgy Applied Metallurgy',
  'JACSC510 Microbiology Applied Microbiology',
  'JACSC710 Molecular Biology, Biophysics and Biochemistry Applied Molecular Biology, Biophysics and Biochemistry',
  'JACSF310 Physics Applied Physics',
  'JACSC810 Psychology Applied Psychology',
  'JACSL310 Sociology Applied Sociology',
  'JACSG310 Statistics Applied Statistics',
  'JACSC310 Zoology Applied Zoology',
  'JACSD435 Fish Farming Aquaculture',
  'JACSD410 Agriculture Arable and Fruit Farming',
  'JACSQ470 Ancient Language studies Aramaic',
  'JACSF420 Forensic and Archaeological Science Archaeological Science',
  'JACSV450 Archaeology Archaeological conservation',
  'JACSV460 Archaeology Archaeological techniques',
  'JACSV400 Historical and Philosophical studies Archaeology',
  'JACSV490 Archaeology Archaeology not elsewhere classified',
  'JACSK110 Architecture Architectural Design Theory',
  'JACSK130 Architecture Architectural Technology',
  'JACSK100 Architecture, Building and Planning Architecture',
  'JACSK190 Architecture Architecture not elsewhere classified',
  'JACSK Reporting - JACS Architecture, Building and Planning',
  'JACSK990 Others in Architecture, Building and Planning Architecture, Building and Planning not elsewhere classified',
  'JACSP132 Curatorial studies Archive studies',
  'JACSB344 Alternative Medicine Aromatherapy',
  'JACSG700 Mathematical and Computer Sciences Artificial Intelligence',
  'JACSG790 Artificial Intelligence Artificial Intelligence not elsewhere classified',
  'JACSV240 History by area Asian History',
  'JACSV644 Religious writings Asian religious texts',
  'JACSH420 Aerospace Engineering Astronautical Engineering',
  'JACSF500 Physical Sciences Astronomy',
  'JACSF590 Astronomy Astronomy not elsewhere classified',
  'JACSF510 Astronomy Astrophysics',
  'JACSF331 Environmental Physics Atmospheric Physics',
  'JACSH820 Chemical, Process and Energy Engineering Atomic Engineering',
  'JACSJ930 Others in Technology Audio Technology',
  'JACSN721 Secretarial and Typing skills Audio Typing',
  'JACSB610 Aural and Oral Sciences Audiology',
  'JACSN421 Accounting Theory Auditing of Accounts',
  'JACSB600 Subjects allied to Medicine Aural and Oral Sciences',
  'JACSB690 Aural and Oral Sciences Aural and Oral Sciences not elsewhere classified',
  'JACSV260 History by area Australasian History',
  'JACST810 Australasian studies Australasian Language studies',
  'JACST820 Australasian studies Australasian Literature studies',
  'JACST830 Australasian studies Australasian Society and Culture studies',
  'JACST800 Eastern, Asiatic, African, American and Australasian Languages, Literature and related subjects Australasian studies',
  'JACST890 Australasian studies Australasian studies not elsewhere classified',
  'GLI029 Government Led Initiatives Australia',
  'JACSV261 Australasian History Australian History',
  'JACSL221 Political Systems Autocracy',
  'JACSH131 Computer-Aided Engineering Automated Engineering Design',
  'JACSG761 Machine Learning Automated Reasoning',
  'JACSH330 Mechanical Engineering Automotive Engineering',
  'JACSH460 Aerospace Engineering Aviation studies',
  'JACSH430 Aerospace Engineering Avionics',
  'GLI014 Government Led Initiatives Ayrton Fund',
  'JACSC530 Microbiology Bacteriology',
  'JACSN310 Finance Banking',
  'FRAS2 Reporting - FRASCATI Basic - orientated',
  'FRAS1 Reporting - FRASCATI Basic - pure',
  'JACSW761 Reed Crafts Basketry',
  'JACSC120 Biology Behavioural Biology',
  'JACSF163 Organic Chemistry Bio-organic Chemistry',
  'JACSH811 Chemical Engineering Biochemical Engineering',
  'JACSC181 Ecology Biodiversity',
  'JACSH673 Robotics and Cybernetics Bioengineering',
  'JACSF811 Environmental Geography Biogeography',
  'JACSC720 Molecular Biology, Biophysics and Biochemistry Biological Chemistry',
  'JACSC Reporting - JACS Biological Sciences',
  'JACSC990 Others in Biological Sciences Biological Sciences not elsewhere classified',
  'JACSC100 Biological Sciences Biology',
  'JACSC190 Biology Biology not elsewhere classified',
  'JACSB830 Medical Technology Biomechanics, Biomaterials and Prosthetics (non-clinical)',
  'JACSC191 Biology not elsewhere classified Biometry',
  'JACSF165 Organic Chemistry Biomolecular Chemistry',
  'JACSC760 Molecular Biology, Biophysics and Biochemistry Biomolecular Science',
  'JACSC770 Molecular Biology, Biophysics and Biochemistry Biophysical Science',
  'JACSH831 Chemical Process Engineering Bioprocess Engineering',
  'JACSC560 Microbiology Biotechnology',
  'JACSW722 Metal Crafts Blacksmithing',
  'JACSW520 Dance Body Awareness',
  'JACSN413 Accountancy Book-keeping',
  'JACSW781 Paper Crafts Bookbinding',
  'JACSC200 Biological Sciences Botany',
  'JACSC290 Botany Botany not elsewhere classified',
  'JACSQ580 Celtic studies Breton',
  'JACSQ581 Breton Breton Literature',
  'JACSV210 History by area British History',
  'JACSH642 Communications Engineering Broadcast Engineering',
  'JACSV430 Archaeology Bronze Age',
  'JACSQ522 Modern Celtic studies Brythonic group of languages',
  'JACSV625 Religious studies Buddhism',
  'JACSK200 Architecture, Building and Planning Building',
  'JACSK230 Building Building Surveying',
  'JACSK210 Building Building Technology',
  'JACSK290 Building Building not elsewhere classified',
  'JACSN Reporting - JACS Business and Administrative studies',
  'JACSN990 Others in Business and Administrative studies Business and Administrative studies not elsewhere classified',
  'JACSM221 Private Law Business and Commercial Law',
  'JACSN100 Business and Administrative studies Business studies',
  'JACSN190 Business studies Business studies not elsewhere classified',
  'JACSV120 History by period Byzantine History',
  'GLI012 Government Led Initiatives COVID-19',
  'GLI013 Government Led Initiatives COVID-19 (re-purposed)',
  'JACSW732 Wood Crafts Cabinet making',
  'JACSW150 Fine Art Calligraphy',
  'GLI017 Government Led Initiatives Canada',
  'JACSV231 American History Canadian History',
  'JACSL171 Economic Systems Capitalism',
  'JACSB810 Medical Technology Cardiography',
  'JACSL550 Social Work Careers Guidance',
  'JACSW731 Wood Crafts Carpentry/Joinery',
  'JACSF831 Topography Cartography',
  'JACSC130 Biology Cell Biology',
  'JACSC320 Zoology Cell Zoology',
  'JACSB131 Pathology Cellular Pathology',
  'JACSQ500 Linguistics, Classics and related subjects Celtic studies',
  'JACSQ590 Celtic studies Celtic studies not elsewhere classified',
  'JACSV252 African History Central African History',
  'JACSV234 American History Central American History',
  'JACSJ310 Ceramics and Glasses Ceramics',
  'JACSW270 Design studies Ceramics Design',
  'JACSJ300 Technologies Ceramics and Glasses',
  'JACSJ390 Ceramics and Glasses Ceramics and Glasses not elsewhere classified',
  'JACSD612 Food Science Cereal Science',
  'JACSN214 Management Techniques Change Management',
  'JACSH810 Chemical, Process and Energy Engineering Chemical Engineering',
  'JACSF320 Physics Chemical Physics',
  'JACSH830 Chemical, Process and Energy Engineering Chemical Process Engineering',
  'JACSH800 Engineering Chemical, Process and Energy Engineering',
  'JACSH890 Chemical, Process and Energy Engineering Chemical, Process and Energy Engineering not elsewhere classified',
  'JACSF100 Physical Sciences Chemistry',
  'JACSF190 Chemistry Chemistry not elsewhere classified',
  'JACSL520 Social Work Child Care',
  'GLI024 Government Led Initiatives China',
  'JACSB341 Alternative Medicine Chinese',
  'JACSV241 Asian History Chinese History',
  'JACST110 Chinese studies Chinese Language Studies',
  'JACSQ181 Linguistics of non-English, non-European Languages Chinese Linguistics',
  'JACST120 Chinese studies Chinese Literature Studies',
  'JACST130 Chinese studies Chinese Society and Culture studies',
  'JACST100 Eastern, Asiatic, African, American and Australasian Languages, Literature and related subjects Chinese studies',
  'JACST190 Chinese studies Chinese studies not elsewhere classified',
  'JACSB330 Complementary Medicine Chiropody',
  'JACSB320 Complementary Medicine Chiropractic',
  'JACSW510 Dance Choreography',
  'JACSV621 Religious studies Christian studies',
  'JACSQ611 Latin Language Church Latin',
  'JACSW600 Creative Arts and Design Cinematics and Photography',
  'JACSW690 Cinematics and Photography Cinematics and Photography not elsewhere classified',
  'JACSW620 Cinematics and Photography Cinematography',
  'JACSH200 Engineering Civil Engineering',
  'JACSH290 Civil Engineering Civil Engineering not elsewhere classified',
  'JACSQ420 Ancient Language studies Classical Arabic',
  'JACSQ711 Classical Greek Language Classical Church Greek',
  'JACSQ710 Classical Greek studies Classical Greek Language',
  'JACSQ720 Classical Greek studies Classical Greek Literature',
  'JACSQ730 Classical Greek studies Classical Greek Literature in Translation',
  'JACSQ700 Linguistics, Classics and related subjects Classical Greek studies',
  'JACSQ790 Classical Greek studies Classical Greek studies not elsewhere classified',
  'JACSQ800 Linguistics, Classics and related subjects Classical studies',
  'JACSQ890 Classical studies Classical studies not elsewhere classified',
  'JACSW750 Crafts Clay and Stone Crafts',
  'GCA2 GCRF Challenge Areas Clean air, water and sanitation',
  'JACSF860 Physical and Terrestrial Geographical and Environmental Sciences Climatology',
  'JACSA400 Medicine and Dentistry Clinical Dentistry',
  'JACSA300 Medicine and Dentistry Clinical Medicine',
  'JACSC840 Psychology Clinical Psychology',
  'JACSD220 Clinical Veterinary Medicine and Dentistry Clinical Veterinary Dentistry',
  'JACSD210 Clinical Veterinary Medicine and Dentistry Clinical Veterinary Medicine',
  'JACSD200 Veterinary Sciences, Agriculture and related subjects Clinical Veterinary Medicine and Dentistry',
  'JACSD290 Clinical Veterinary Medicine and Dentistry Clinical Veterinary Medicine and Dentistry not elsewhere classified',
  'JACSW723 Metal Crafts Clock/Watchmaking',
  'JACSJ440 Polymers and Textiles Clothing Production',
  'JACSW230 Design studies Clothing/Fashion Design',
  'JACSH222 Environmental Engineering Coastal Decay',
  'JACSG750 Artificial Intelligence Cognitive Modelling',
  'JACSC850 Psychology Cognitive Psychology',
  'JACSL174 Economic Systems Collectivism',
  'JACSF112 Applied Chemistry Colour Chemistry',
  'JACSJ442 Clothing Production Commercial Tailoring',
  'JACSL242 International Politics Commonwealth Politics',
  'JACSH640 Electronic and Electrical Engineering Communications Engineering',
  'JACSD517 Trees and Shrubs Community Forestry',
  'JACSB710 Nursing Community Nursing',
  'JACSL540 Social Work Community Work',
  'JACSM140 Law by area Comparative Law',
  'JACSQ200 Linguistics, Classics and related subjects Comparative Literary studies',
  'JACSQ290 Comparative Literary studies Comparative Literary studies not elsewhere classified',
  'JACSL260 Politics Comparative Politics',
  'JACSV627 Religious studies Comparative Religious studies',
  'JACSV645 Religious writings Comparative religious texts',
  '3PTY0000100001 TSB Complementary',
  'JACSB300 Subjects allied to Medicine Complementary Medicine',
  'JACSB390 Complementary Medicine Complementary Medicine not elsewhere classified',
  'JACSF343 Mathematical & Theoretical Physics Computational Physics',
  'JACSG430 Computer Science Computational Science Foundations',
  'JACSG411 Computer Architectures & Operating Systems Computer Architectures',
  'JACSG410 Computer Science Computer Architectures & Operating Systems',
  'JACSG400 Mathematical and Computer Sciences Computer Science',
  'JACSG740 Artificial Intelligence Computer Vision',
  'JACSH130 General Engineering Computer-Aided Engineering',
  'JACSG490 Computer Science Computing Science not elsewhere classified',
  'JACSK250 Building Conservation of Buildings',
  'JACSL212 Political Theories Conservatism',
  'JACSK220 Building Construction Management',
  'JACSM222 Private Law Contract Law',
  'JACSH660 Electronic and Electrical Engineering Control Systems',
  'JACSH662 Control Systems Control by light systems',
  'EUC2 EU Classifications Coordination and Support Actions',
  'JACSQ411 Ancient Egyptian Coptic',
  'JACSQ570 Celtic studies Cornish',
  'JACSQ571 Cornish Cornish Literature',
  'JACSN562 Promotion and Advertising Corporate Image',
  'JACSJ230 Metallurgy Corrosion Technology',
  'JACSN411 Accountancy Cost and Management Accountancy',
  'JACSB940 Others in Subjects allied to Medicine Counselling',
  'JACSW700 Creative Arts and Design Crafts',
  'JACSW790 Crafts Crafts not elsewhere classified',
  'JACSW Reporting - JACS Creative Arts and Design',
  'JACSW990 Others in Creative Arts and Design Creative Arts and Design not elsewhere classified',
  'JACSN212 Management Techniques Creative Management',
  'JACSM211 Public Law Criminal Law',
  'JACSB771 Medical Nursing Critical Care Nursing',
  'JACSD413 Arable and Fruit Farming Crop Nutrition',
  'JACSD412 Arable and Fruit Farming Crop Physiology',
  'JACSD415 Arable and Fruit Farming Crop Production',
  'JACSD414 Arable and Fruit Farming Crop Protection',
  'JACSF131 Structural Chemistry Crystallography',
  'JACSL726 Human and Social Geography by topic Cultural Geography',
  'NABS110 Reporting - NABS Culture, recreation, religion and mass media',
  'JACSP130 Information Services Curatorial studies',
  'JACSH672 Robotics and Cybernetics Cybernetics',
  'JACSR713 Russian and East European Languages Czech Language',
  'JACSR723 Russian and East European Literature Czech Literature',
  'JACSR733 Russian and East European Society and Culture Czech Society and Culture',
  'GLI009 Government Led Initiatives DFID (Department for International Development)',
  'JACSW500 Creative Arts and Design Dance',
  'JACSW590 Dance Dance not elsewhere classified',
  'JACSR614 Scandinavian Languages Danish Language',
  'JACSR624 Scandinavian Literature Danish Literature',
  'JACSR634 Scandinavian Society and Culture Danish Society and Culture',
  'JACSG560 Information Systems Data Management',
  'JACSG540 Information Systems Databases',
  'JACSG623 Programming Declarative Programming',
  'NABS114 Reporting - NABS Defence',
  'JACSL222 Political Systems Democracy',
  'JACSB750 Nursing Dental Nursing',
  'JACSB840 Medical Technology Dental Technology',
  'JACSW200 Creative Arts and Design Design studies',
  'JACSW290 Design studies Design studies not elsewhere classified',
  'JACSC141 Developmental/Reproductive Biology Developmental Biology',
  'JACSC820 Psychology Developmental Psychology',
  'JACSC330 Zoology Developmental Zoology',
  'JACSC140 Biology Developmental/Reproductive Biology',
  'JACSB410 Nutrition Dietetics',
  'JACSH651 Systems Engineering Digital Circuit Engineering',
  'CSES0000300005 RCUK Programmes Digital Economy',
  'JACSW611 Moving Image Techniques Directing Motion Pictures',
  'JACSW420 Drama Directing for Theatre',
  'JACSL340 Sociology Disability in Society',
  'JACSN530 Marketing Distribution',
  'JACSB711 Community Nursing District Nursing',
  'JACSV630 Theology and Religious studies Divinity',
  'JACSN223 Institutional Management Domestic Management',
  'JACSW400 Creative Arts and Design Drama',
  'JACSW490 Drama Drama not elsewhere classified',
  'JACSW110 Fine Art Drawing',
  'JACSW712 Fabric and Leather Crafts Dressmaking',
  'JACSR911 Other European Languages Dutch',
  'JACSJ422 Textiles Technology Dying and Colouring of Textiles',
  'JACSH310 Mechanical Engineering Dynamics',
  'EUC5 EU Classifications ERA-NET Cofund',
  'EUC33 EU Classifications ERC – ADG',
  'EUC32 EU Classifications ERC – COG',
  'EUC24 EU Classifications ERC – POC',
  'EUC25 EU Classifications ERC – SYG',
  'EUC31 EU Classifications ERC – StG',
  'EUC  EU Classifications',
  'JACSF640 Geology Earth Science',
  'JACSV254 African History East African History',
  'JACST Reporting - JACS Eastern, Asiatic, African, American and Australasian Languages, Literature and related subjects',
  'JACST990 Others in Eastern, Asiatic, African, American and Australasian Languages, Literature and related subjects Eastern, Asiatic, African, American and Australasian Languages, Literature and related subjects not elsewhere classified',
  'JACSC180 Biology Ecology',
  'JACSL140 Economics Econometrics',
  'JACSL721 Human and Social Geography by topic Economic Geography',
  'JACSV310 History by topic Economic History',
  'JACSL113 Applied Economics Economic Policy',
  'JACSL170 Economics Economic Systems',
  'JACSL100 Social studies Economics',
  'JACSL190 Economics Economics not elsewhere classified',
  'JACSX Reporting - JACS Education',
  'NABS109 Reporting - NABS Education',
  'JACSL433 Public Policy Education Policy',
  'JACSX990 Others in Education Education not elsewhere classified',
  'JACSC812 Applied Psychology Educational Psychology',
  'JACSV410 Archaeology Egyptology',
  'JACSH620 Electronic and Electrical Engineering Electrical Engineering',
  'JACSH630 Electronic and Electrical Engineering Electrical Power',
  'JACSH632 Electrical Power Electrical Power Distribution',
  'JACSH631 Electrical Power Electrical Power Generation',
  'JACSF341 Mathematical & Theoretical Physics Electromagnetism',
  'JACSH360 Mechanical Engineering Electromechanical Engineering',
  'JACSH610 Electronic and Electrical Engineering Electronic Engineering',
  'JACSP304 Media studies Electronic Media studies',
  'JACSP410 Publishing Electronic Publishing',
  'JACSH600 Engineering Electronic and Electrical Engineering',
  'JACSH690 Electronic and Electrical Engineering Electronic and Electrical Engineering not elsewhere classified',
  'NABS105 Reporting - NABS Energy',
  'CSES0000300002 RCUK Programmes Energy Programme',
  'JACSH221 Environmental Engineering Energy Resources',
  'JACSJ910 Others in Technology Energy Technologies',
  'JACSH Reporting - JACS Engineering',
  'JACSH150 General Engineering Engineering Design',
  'JACSF612 Applied Geology Engineering Geology',
  'JACSJ511 Materials Technology Engineering Materials',
  'JACSF311 Applied Physics Engineering Physics',
  'JACSH242 Surveying Science Engineering Surveying',
  'JACSH990 Others in Engineering Engineering not elsewhere classified',
  'JACSG160 Mathematics Engineering/Industrial Mathematics',
  'JACSV214 British History English History',
  'JACSQ310 English studies English Language',
  'JACSM111 UK Legal Systems English Law',
  'JACSQ160 Linguistics English Linguistics',
  'JACSQ320 English studies English Literature',
  'JACSQ322 English Literature English Literature by author',
  'JACSQ321 English Literature English Literature by period',
  'JACSQ323 English Literature English Literature by topic',
  'JACSQ340 English studies English Literature written as a second language',
  'JACSQ330 English studies English as a second language',
  'JACSQ300 Linguistics, Classics and related subjects English studies',
  'JACSQ390 English studies English studies not elsewhere classified',
  'JACSC340 Zoology Entomology',
  'NABS102 Reporting - NABS Environment',
  'JACSC150 Biology Environmental Biology',
  'JACSF140 Chemistry Environmental Chemistry',
  'JACSD447 Rural Estate Management Environmental Conservation',
  'JACSH220 Civil Engineering Environmental Engineering',
  'JACSF810 Physical and Terrestrial Geographical and Environmental Sciences Environmental Geography',
  'JACSB910 Others in Subjects allied to Medicine Environmental Health',
  'JACSH223 Environmental Engineering Environmental Impact Assessment',
  'JACSF330 Physics Environmental Physics',
  'JACSF850 Physical and Terrestrial Geographical and Environmental Sciences Environmental Sciences',
  'JACSL217 Political Theories Environmentalism',
  'JACSV511 Metaphysics Epistemology',
  'JACSD422 Livestock Equine studies',
  'JACSJ920 Others in Technology Ergonomics',
  'JACSL330 Sociology Ethnic studies',
  'EUC9 EU Classifications Euratom Nuclear Fission',
  'JACSN110 Business studies European Business studies',
  'JACSV220 History by area European History',
  'JACSR Reporting - JACS European Languages, Literature and related subjects',
  'JACSR990 Others in European Languages, Literature and related subjects European Languages, Literature and related subjects not elsewhere classified',
  'EUC7 EU Classifications European Research Council (ERC) Frontier Grants',
  'JACSM120 Law by area European Union Law',
  'JACSL241 International Politics European Union Politics',
  'JACSN820 Tourism, Transport and Travel Event Management',
  'JACSC182 Ecology Evolution',
  'JACSD425 Livestock Exotic Livestock',
  'JACSD418 Arable and Fruit Farming Exotic Plants and Crops',
  'JACSC830 Psychology Experimental Psychology',
  'FRAS5 Reporting - FRASCATI Experimental development',
  'JACSF621 Mining Geology Exploration Geology',
  'JACSF661 Geophysics Exploration Geophysics',
  'NABS103 Reporting - NABS Exploration and exploitation of space',
  'NABS101 Reporting - NABS Exploration and exploitation of the earth  ',
  'GLI011 Government Led Initiatives FIC (Fund for International Collaboration)',
  'EUC14 EU Classifications FP7 Framework Programme 7',
  'EUC15 EU Classifications FPA Framework Partnership Agreement',
  'JACSW710 Crafts Fabric and Leather Crafts',
  'JACSP510 Journalism Factual Reporting',
  'JACSV323 Social History Family History',
  'JACSD441 Rural Estate Management Farm Management',
  'JACSL215 Political Theories Fascism',
  'EUC4 EU Classifications Fast Track to innovation instrument',
  'JACSL216 Political Theories Feminism',
  'JACSW613 Moving Image Techniques Film & Sound Recording',
  'JACSP313 Media Production Film Production',
  'JACSP303 Media studies Film studies',
  'JACSN300 Business and Administrative studies Finance',
  'JACSN390 Finance Finance not elsewhere classified',
  'JACSL111 Applied Economics Financial Economics',
  'JACSN340 Finance Financial Management',
  'JACSN422 Accounting Theory Financial Reporting',
  'JACSN341 Financial Management Financial Risk',
  'JACSW100 Creative Arts and Design Fine Art',
  'JACSW160 Fine Art Fine Art Conservation',
  'JACSW190 Fine Art Fine Art not elsewhere classified',
  'JACSR613 Scandinavian Languages Finnish Language',
  'JACSR623 Scandinavian Literature Finnish Literature',
  'JACSR633 Scandinavian Society and Culture Finnish Society and Culture',
  'JACSH121 Safety Engineering Fire Safety Engineering',
  'JACSD430 Agriculture Fish Farming',
  'JACSD431 Fish Farming Fish Husbandry',
  'JACSR912 Other European Languages Flemish',
  'JACSH441 Aerodynamics Flight Mechanics',
  'JACSH141 Mechanics Fluid Mechanics',
  'JACSD620 Food and Beverage studies Food Hygiene',
  'JACSD610 Food and Beverage studies Food Science',
  'JACSD642 Food and Beverages for the Consumer Food and Beverage Delivery',
  'JACSD631 Food and Beverage Production Food and Beverage Manufacture',
  'JACSD632 Food and Beverage Production Food and Beverage Processing',
  'JACSD630 Food and Beverage studies Food and Beverage Production',
  'JACSD633 Food and Beverage Production Food and Beverage Technology',
  'JACSD600 Veterinary Sciences, Agriculture and related subjects Food and Beverage studies',
  'JACSD641 Food and Beverages for the Consumer Food and Beverages Packaging',
  'JACSD640 Food and Beverage studies Food and Beverages for the Consumer',
  'JACSD690 Food and Beverage studies Food studies not elsewhere classified',
  'JACSJ445 Clothing Production Footwear production',
  'JACSF410 Forensic and Archaeological Science Forensic Science',
  'JACSF490 Forensic and Archaeological Science Forensic Science not elsewhere classified',
  'JACSF400 Physical Sciences Forensic and Archaeological Science',
  'JACSD500 Veterinary Sciences, Agriculture and related subjects Forestry',
  'JACSD541 Forestry Technology Forestry Irrigation and Drainage',
  'JACSD511 Trees and Shrubs Forestry Pests and Diseases',
  'JACSD540 Forestry Forestry Technology',
  'JACSD590 Forestry Forestry not elsewhere classified',
  'GLI030 Government Led Initiatives France',
  'JACSV221 European History French History',
  'JACSR110 French studies French Language',
  'JACSQ171 Linguistics of non-English European Languages French Linguistics',
  'JACSR120 French studies French Literature',
  'JACSR130 French studies French Society and Culture',
  'JACSR100 European Languages, Literature and related subjects French studies',
  'JACSR190 French studies French studies not elsewhere classified',
  'JACSC162 Marine/Freshwater Biology Freshwater Biology',
  'JACSD432 Fish Farming Freshwater Fish',
  'JACSD614 Food Science Fruit Science',
  'JACSW260 Design studies Furniture Design',
  'JACSJ513 Materials Technology Furniture Technology',
  'CSES0000300008 RCUK Programmes GCRF',
  'CSES0000300010 RCUK Programmes GCRF Challenge Areas',
  'JACSD424 Livestock Game keeping',
  'JACSD442 Rural Estate Management Gamekeeping Management',
  'JACSH840 Chemical, Process and Energy Engineering Gas Engineering',
  'JACSJ530 Materials Technology not otherwise specified Gemmology',
  'JACSL320 Sociology Gender studies',
  'JACSH100 Engineering General Engineering',
  'JACSH190 General Engineering General Engineering not elsewhere classified',
  'JACSH241 Surveying Science General Practice Surveying',
  'NABS112 Reporting - NABS General advancement of knowledge: R&D financed from General University Funds (GUF)',
  'NABS113 Reporting - NABS General advancement of knowledge: R&D financed from other sources than GUF',
  'JACSC400 Biological Sciences Genetics',
  'JACSC490 Genetics Genetics not elsewhere classified',
  'JACSF670 Geology Geochemistry',
  'JACSF891 Geographical and Environmental Sciences not elsewhere classified Geographical Information Systems',
  'JACSF890 Physical and Terrestrial Geographical and Environmental Sciences Geographical and Environmental Sciences not elsewhere classified',
  'JACSF650 Geology Geological Oceanography',
  'JACSF600 Physical Sciences Geology',
  'JACSF690 Geology Geology not elsewhere classified',
  'JACSF820 Physical and Terrestrial Geographical and Environmental Sciences Geomorphology',
  'JACSF660 Geology Geophysics',
  'JACSF642 Earth Science Geoscience',
  'JACSH250 Civil Engineering Geotechnical Engineering',
  'JACSF630 Geology Geotechnology',
  'JACSB741 Adult Nursing Geriatric Nursing',
  'JACSV222 European History German History',
  'JACSR210 German studies German Language',
  'JACSQ172 Linguistics of non-English European Languages German Linguistics',
  'JACSR220 German studies German Literature',
  'JACSR230 German studies German Society and Culture',
  'JACSR200 European Languages, Literature and related subjects German studies',
  'JACSR290 German studies German studies not elsewhere classified',
  'GLI025 Government Led Initiatives Germany',
  'JACSW770 Crafts Glass Crafts',
  'JACSJ320 Ceramics and Glasses Glass Technology',
  'JACSW771 Glass Crafts Glassblowing',
  'JACSD416 Arable and Fruit Farming Glasshouse Culture',
  'CSES0000300007 RCUK Programmes Global Food Security',
  'CSES0000300004 RCUK Programmes Global Uncertainties',
  'JACSQ521 Modern Celtic studies Goidelic group of languages',
  'GLI  Government Led Initiatives',
  'JACSW210 Design studies Graphic Design',
  'NABS107 Reporting - NABS Health',
  'JACSL510 Social Work Health & Welfare',
  'JACSL431 Public Policy Health Policy',
  'JACSC841 Clinical Psychology Health Psychology',
  'JACSB712 Community Nursing Health Visiting',
  'JACSN620 Human Resource Management Health and Safety Issues',
  'JACSQ480 Ancient Language studies Hebrew',
  'JACSB342 Alternative Medicine Herbalism',
  'JACSD445 Rural Estate Management Heritage Management',
  'JACSV624 Religious studies Hinduism',
  'JACSL725 Human and Social Geography by topic Historical Geography',
  'JACSQ120 Linguistics Historical Linguistics',
  'JACSV Reporting - JACS Historical and Philosophical studies',
  'JACSV990 Others in Historical and Philosophical studies Historical and Philosophical studies not elsewhere classified',
  'JACSV290 History by area History by Area not elsewhere classified',
  'JACSV190 History by period History by Period not elsewhere classified',
  'JACSV390 History by topic History by Topic not elsewhere classified',
  'JACSV200 Historical and Philosophical studies History by area',
  'JACSV100 Historical and Philosophical studies History by period',
  'JACSV300 Historical and Philosophical studies History by topic',
  'JACSV360 History by topic History of Architecture',
  'JACSV350 History by topic History of Art',
  'JACSV382 History of Science History of Chemistry',
  'JACSW631 History of Cinematics and Photography History of Cinematics',
  'JACSW630 Cinematics and Photography History of Cinematics and Photography',
  'JACSW530 Dance History of Dance',
  'JACSV370 History by topic History of Design',
  'JACSV383 History of Science History of Mathematics',
  'JACSW330 Music History of Music',
  'JACSW632 History of Cinematics and Photography History of Photography',
  'JACSV381 History of Science History of Physics',
  'JACSV330 History by topic History of Religions',
  'JACSV380 History by topic History of Science',
  'JACSN221 Institutional Management Hotel and Catering',
  'JACSK450 Planning (Urban, Rural and Regional) Housing',
  'JACSC420 Genetics Human Genetics',
  'JACSN600 Business and Administrative studies Human Resource Management',
  'JACSN690 Human Resource Management Human Resources not elsewhere classified',
  'JACSL700 Social studies Human and Social Geography',
  'JACSL710 Human and Social Geography Human and Social Geography by area',
  'JACSL720 Human and Social Geography Human and Social Geography by topic',
  'JACSL790 Human and Social Geography Human and Social Geography not elsewhere classified',
  'JACSL713 Human and Social Geography by area Human and Social Geography of Africa',
  'JACSL716 Human and Social Geography by area Human and Social Geography of Arctic/Antarctic',
  'JACSL712 Human and Social Geography by area Human and Social Geography of Asia',
  'JACSL714 Human and Social Geography by area Human and Social Geography of Australasia',
  'JACSL711 Human and Social Geography by area Human and Social Geography of Europe',
  'JACSL715 Human and Social Geography by area Human and Social Geography of the Americas',
  'JACSG440 Computer Science Human-computer Interaction',
  'JACSF720 Ocean Sciences Hydrography',
  'JACSF852 Environmental Sciences Hydrology',
  'JACSB345 Alternative Medicine Hypnotherapy',
  'GLI003 Government Led Initiatives ISCF',
  'GLI016 Government Led Initiatives ISPF Non-ODA',
  'GLI015 Government Led Initiatives ISPF ODA',
  'JACSV224 European History Iberian History',
  'JACSW220 Design studies Illustration',
  'JACSW800 Creative Arts and Design Imaginative Writing',
  'JACSW890 Imaginative Writing Imaginative Writing not elsewhere classified',
  'JACSC550 Microbiology Immunology',
  'GCA3 GCRF Challenge Areas Inclusive and equitable quality education',
  'GLI018 Government Led Initiatives India',
  'JACSV242 Asian History Indian History',
  'JACSD634 Food and Beverage Production Industrial Baking',
  'JACSJ700 Technologies Industrial Biotechnology',
  'JACSJ790 Industrial Biotechnology Industrial Biotechnology not elsewhere classified',
  'JACSD635 Food and Beverage Production Industrial Brewing',
  'JACSF111 Applied Chemistry Industrial Chemistry',
  'JACSF611 Applied Geology Industrial Geology',
  'JACSJ942 Machinery Maintenance Industrial Machinery Maintenance',
  'JACSN611 Unknown Listing in JACS Industrial Relations',
  'NABS106 Reporting - NABS Industrial production and technology',
  'JACSW240 Design studies Industrial/Product Design',
  'JACSP110 Information Services Information Management',
  'JACSG510 Information Systems Information Modelling',
  'JACSP100 Mass Communications and Documentation Information Services',
  'JACSP190 Information Services Information Services not elsewhere classified',
  'JACSG500 Mathematical and Computer Sciences Information Systems',
  'JACSF120 Chemistry Inorganic Chemistry',
  'JACSN220 Management studies Institutional Management',
  'JACSH661 Control Systems Instrumentation Control',
  'JACSN322 Investment and Insurance Insurance',
  'JACSH612 Electronic Engineering Integrated Circuit Design',
  'JACSH110 General Engineering Integrated Engineering',
  'JACSV340 History by topic Intellectual History',
  'JACSP430 Publishing Interactive Publishing',
  'JACSW280 Design studies Interactive and Electronic Design',
  'JACSK120 Architecture Interior Architecture',
  'JACSW250 Design studies Interior Design',
  'CSES0000300011 RCUK Programmes International',
  'JACSD450 Agriculture International Agriculture',
  'JACSN120 Business studies International Business studies',
  'JACSL244 International Politics International Constitutional studies',
  'JACSL160 Economics International Economics',
  'JACSD520 Forestry International Forestry',
  'JACSV271 World History International History',
  'JACSN550 Marketing International Marketing',
  'JACSL240 Politics International Politics',
  'JACSL250 Politics International Relations',
  'JACSL420 Social Policy International Social Policy',
  'JACSN840 Tourism, Transport and Travel International Tourism',
  'JACSN321 Investment and Insurance Investment',
  'JACSN320 Finance Investment and Insurance',
  'GLI031 Government Led Initiatives Ireland',
  'JACSQ540 Celtic studies Irish Gaelic',
  'JACSQ541 Irish Gaelic Irish Gaelic Literature',
  'JACSV211 British History Irish History',
  'JACSV440 Archaeology Iron Age',
  'JACSV622 Religious studies Islamic studies',
  'GLI019 Government Led Initiatives Israel',
  'JACSV223 European History Italian History',
  'JACSR310 Italian studies Italian Language',
  'JACSQ173 Linguistics of non-English European Languages Italian Linguistics',
  'JACSR320 Italian studies Italian Literature',
  'JACSR330 Italian studies Italian Society and Culture',
  'JACSR300 European Languages, Literature and related subjects Italian studies',
  'JACSR390 Italian studies Italian studies not elsewhere classified',
  'GLI020 Government Led Initiatives Japan',
  'JACST210 Japanese studies Japanese Language studies',
  'JACSQ182 Linguistics of non-English, non-European Languages Japanese Linguistics',
  'JACST220 Japanese studies Japanese Literature studies',
  'JACST230 Japanese studies Japanese Society and Culture studies',
  'JACST200 Eastern, Asiatic, African, American and Australasian Languages, Literature and related subjects Japanese studies',
  'JACST290 Japanese studies Japanese studies not elsewhere classified',
  'JACSP500 Mass Communications and Documentation Journalism',
  'JACSP590 Journalism Journalism not elsewhere classified',
  'JACSV623 Religious studies Judaism',
  'JACSM240 Law by Topic Jurisprudence',
  'JACSL173 Economic Systems Keynesianism',
  'JACSG720 Artificial Intelligence Knowledge Representation',
  'JACSN231 Land and property management Land Management',
  'JACSD444 Rural Estate Management Land Management for Recreation',
  'JACSN851 Transport Studies Land Travel',
  'JACSN230 Management studies Land and property management',
  'JACSK310 Landscape Design Landscape Architecture',
  'JACSK300 Architecture, Building and Planning Landscape Design',
  'JACSK390 Landscape Design Landscape Design not elsewhere classified',
  'JACSK320 Landscape Design Landscape studies',
  'JACSB630 Aural and Oral Sciences Language Pathology',
  'JACSF361 Optical Physics Laser Physics',
  'JACSQ712 Classical Greek Language Late Greek',
  'JACST711 American Language studies Latin American Language studies',
  'JACST721 American Literature studies Latin American Literature studies',
  'JACST731 American Society and Culture studies Latin American Society and Culture studies',
  'JACSQ610 Latin studies Latin Language',
  'JACSQ620 Latin studies Latin Literature',
  'JACSQ630 Latin studies Latin Literature in Translation',
  'JACSQ600 Linguistics, Classics and related subjects Latin studies',
  'JACSQ690 Latin studies Latin studies not elsewhere classified',
  'JACSM Reporting - JACS Law',
  'JACSM190 Law by area Law by Area not elsewhere classified',
  'JACSM200 Law Law by Topic',
  'JACSM100 Law Law by area',
  'JACSM290 Law by Topic Law by topic not elsewhere classified',
  'JACSM990 Others in Law Law not elsewhere classified',
  'JACSB761 Mental Health Nursing Learning Disability Nursing',
  'JACSJ430 Polymers and Textiles Leather Technology',
  'JACSW715 Fabric and Leather Crafts Leatherwork',
  'JACSM250 Law by Topic Legal Practice',
  'JACSL211 Political Theories Liberalism',
  'JACSP120 Information Services Librarianship',
  'JACSP121 Librarianship Library studies',
  'JACSQ100 Linguistics, Classics and related subjects Linguistics',
  'JACSQ190 Linguistics Linguistics not elsewhere classified',
  'JACSQ185 Linguistics of non-English, non-European Languages Linguistics of African Languages',
  'JACSQ178 Linguistics of non-English European Languages Linguistics of Ancient and Classical Languages',
  'JACSQ184 Linguistics of non-English, non-European Languages Linguistics of Middle-Eastern Languages',
  'JACSQ183 Linguistics of non-English, non-European Languages Linguistics of Other Asian Languages',
  'JACSQ176 Linguistics of non-English European Languages Linguistics of Scandinavian Languages',
  'JACSQ177 Linguistics of non-English European Languages Linguistics of Slavonic and East-European Languages',
  'JACSQ170 Linguistics Linguistics of non-English European Languages',
  'JACSQ180 Linguistics Linguistics of non-English, non-European Languages',
  'JACSQ Reporting - JACS Linguistics, Classics and related subjects',
  'JACSQ990 Others in Linguistics, Classics and related subjects Linguistics, Classics and related subjects not elsewhere classified',
  'JACSQ220 Comparative Literary studies Literature in its original language',
  'JACSQ210 Comparative Literary studies Literature in translation',
  'JACSD420 Agriculture Livestock',
  'JACSD421 Livestock Livestock Husbandry',
  'CSES0000300003 RCUK Programmes Living with Environment Change',
  'JACSV321 Social History Local History',
  'EUC28 EU Classifications MSCA – Cofund',
  'EUC26 EU Classifications MSCA – IF',
  'EUC30 EU Classifications MSCA – ITN',
  'EUC27 EU Classifications MSCA – Night',
  'EUC29 EU Classifications MSCA – Rise',
  'JACSJ441 Clothing Production Machine Knitting',
  'JACSG760 Artificial Intelligence Machine Learning',
  'JACSJ940 Others in Technology Machinery Maintenance',
  'JACSL130 Economics Macroeconomics',
  'JACSN210 Management studies Management Techniques',
  'JACSN224 Institutional Management Management and Organisation of Education',
  'JACSN200 Business and Administrative studies Management studies',
  'JACSN290 Management studies Management studies not elsewhere classified',
  'JACSH712 Manufacturing Systems Engineering Manufacturing Installation Systems',
  'JACSH711 Manufacturing Systems Engineering Manufacturing Systems Design',
  'JACSH710 Production and Manufacturing Engineering Manufacturing Systems Engineering',
  'JACSH714 Manufacturing Systems Engineering Manufacturing Systems Maintenance',
  'JACSQ550 Celtic studies Manx',
  'JACSQ551 Manx Manx Literature',
  'EUC8 EU Classifications Marie Sklodowska-Curie Actions',
  'JACSC161 Marine/Freshwater Biology Marine Biology',
  'JACSF141 Environmental Chemistry Marine Chemistry',
  'JACSF631 Geotechnology Marine Geotechnology',
  'JACSJ611 Marine Technology Marine Navigation',
  'JACSF332 Environmental Physics Marine Physics',
  'JACSJ614 Marine Technology Marine Plumbing',
  'JACSJ612 Marine Technology Marine Radar',
  'JACSJ613 Marine Technology Marine Radio',
  'JACSF710 Ocean Sciences Marine Sciences',
  'JACSJ610 Maritime Technology Marine Technology',
  'JACSC350 Zoology Marine Zoology',
  'JACSC160 Biology Marine/Freshwater Biology',
  'JACSF841 Physical Geography Maritime Geography',
  'JACSJ600 Technologies Maritime Technology',
  'JACSJ690 Maritime Technology Maritime Technology not elsewhere classified',
  'JACSN510 Marketing Market Research',
  'JACSN500 Business and Administrative studies Marketing',
  'JACSN590 Marketing Marketing not elsewhere classified',
  'JACSW733 Wood Crafts Marquetry and Inlaying',
  'JACSP Reporting - JACS Mass Communications and Documentation',
  'JACSP990 Others in Mass Communications and Documentation Mass Communications and Documentation not elsewhere classified',
  'JACSF200 Physical Sciences Materials Science',
  'JACSF290 Materials Science Materials Science not elsewhere classified',
  'JACSJ510 Materials Technology not otherwise specified Materials Technology',
  'JACSJ590 Materials Technology not otherwise specified Materials Technology not elsewhere classified',
  'JACSJ500 Technologies Materials Technology not otherwise specified',
  'JACSF340 Physics Mathematical & Theoretical Physics',
  'JACSG130 Mathematics Mathematical Methods',
  'JACSG150 Mathematics Mathematical Modelling',
  'JACSG350 Statistics Mathematical Statistics',
  'JACSG Reporting - JACS Mathematical and Computer Sciences',
  'JACSG990 Others in Mathematical and Computing Sciences Mathematical and Computing Sciences not elsewhere classified',
  'JACSG100 Mathematical and Computer Sciences Mathematics',
  'JACSG190 Mathematics Mathematics not elsewhere classified',
  'JACSD611 Food Science Meat Science',
  'JACSH300 Engineering Mechanical Engineering',
  'JACSH390 Mechanical Engineering Mechanical Engineering not elsewhere classified',
  'JACSH140 General Engineering Mechanics',
  'JACSG121 Applied Mathematics Mechanics (Mathematical)',
  'JACSH320 Mechanical Engineering Mechanisms and Machines',
  'JACSH730 Production and Manufacturing Engineering Mechatronics',
  'JACSP310 Media studies Media Production',
  'JACSP300 Mass Communications and Documentation Media studies',
  'JACSP390 Media studies Media studies not elsewhere classified',
  'JACSC741 Medical and Veterinary Biochemistry Medical Biochemistry',
  'JACSC431 Medical and Veterinary Genetics Medical Genetics',
  'JACSM260 Law by Topic Medical Law',
  'JACSC521 Medical and Veterinary Microbiology Medical Microbiology',
  'JACSB770 Nursing Medical Nursing',
  'JACSF350 Physics Medical Physics',
  'JACSG311 Applied Statistics Medical Statistics',
  'JACSB800 Subjects allied to Medicine Medical Technology',
  'JACSB890 Medical Technology Medical Technology not elsewhere classified',
  'JACSC740 Molecular Biology, Biophysics and Biochemistry Medical and Veterinary Biochemistry',
  'JACSC430 Genetics Medical and Veterinary Genetics',
  'JACSC520 Microbiology Medical and Veterinary Microbiology',
  'JACSF150 Chemistry Medicinal Chemistry',
  'JACSA Reporting - JACS Medicine and Dentistry',
  'JACSA990 Others in Medicine and Dentistry Medicine and Dentistry not elsewhere classified',
  'JACSV130 History by period Medieval History',
  'JACSQ612 Latin Language Medieval Latin',
  "JACSL322 Gender studies Men's Studies",
  'JACSB760 Nursing Mental Health Nursing',
  'JACSV560 Philosophy Mental Philosophy',
  'JACSC730 Molecular Biology, Biophysics and Biochemistry Metabolic Biochemistry',
  'JACSW720 Crafts Metal Crafts',
  'JACSJ220 Metallurgy Metallic Fabrication',
  'JACSJ200 Technologies Metallurgy',
  'JACSJ290 Metallurgy Metallurgy not elsewhere classified',
  'JACSV510 Philosophy Metaphysics',
  'JACSF861 Climatology Meteorology',
  'JACSC500 Biological Sciences Microbiology',
  'JACSC590 Microbiology Microbiology not elsewhere classified',
  'JACSL120 Economics Microeconomics',
  'JACSH611 Electronic Engineering Microelectronic Engineering',
  'JACSH644 Communications Engineering Microwave Engineering',
  'JACSB720 Nursing Midwifery',
  'JACSV391 History by Topic not elsewhere classified Military History',
  'JACSJ444 Clothing Production Millinery',
  'JACSJ140 Minerals Technology Mineral Processing',
  'JACSJ150 Minerals Technology Minerals Surveying',
  'JACSJ100 Technologies Minerals Technology',
  'JACSJ190 Minerals Technology Minerals Technology not elsewhere classified',
  'JACSJ110 Minerals Technology Mining',
  'JACSF620 Geology Mining Geology',
  'JACSQ520 Celtic studies Modern Celtic studies',
  'JACSV140 History by period Modern History',
  'JACSV141 Modern History Modern History 1500-1599',
  'JACSV142 Modern History Modern History 1600-1699',
  'JACSV143 Modern History Modern History 1700-1799',
  'JACSV144 Modern History Modern History 1800-1899',
  'JACSV145 Modern History Modern History 1900-1919',
  'JACSV146 Modern History Modern History 1920-1949',
  'JACSV147 Modern History Modern History 1950-1999',
  'JACSV148 Modern History Modern History 2000-2099',
  'JACST600 Eastern, Asiatic, African, American and Australasian Languages, Literature and related subjects Modern Middle Eastern studies',
  'JACST610 Modern Middle Eastern studies Modern Middle-Eastern Language studies',
  'JACST620 Modern Middle Eastern studies Modern Middle-Eastern Literature studies',
  'JACST630 Modern Middle Eastern studies Modern Middle-Eastern Society and Culture studies',
  'JACST690 Modern Middle Eastern studies Modern Middle-Eastern studies not elsewhere classified',
  'JACSC700 Biological Sciences Molecular Biology, Biophysics and Biochemistry',
  'JACSC790 Molecular Biology, Biophysics and Biochemistry Molecular Biology, Biophysics and Biochemistry not elsewhere classified',
  'JACSC440 Genetics Molecular Genetics',
  'JACSL172 Economic Systems Monetarism',
  'JACSV520 Philosophy Moral Philosophy',
  'JACSB850 Medical Technology Mortuary Technology',
  'JACSW610 Cinematics and Photography Moving Image Techniques',
  'JACSG450 Computer Science Multi-media Computing Science',
  'JACSP420 Publishing Multi-media Publishing',
  'JACSW212 Graphic Design Multimedia Design',
  'JACSP131 Curatorial studies Museum studies',
  'JACSW300 Creative Arts and Design Music',
  'JACSJ931 Audio Technology Music Recording',
  'JACSW390 Music Music not elsewhere classified',
  'JACSW360 Music Musical Instrument History',
  'JACSJ950 Others in Technology Musical Instrument Technology',
  'JACSW310 Music Musicianship/Performance studies',
  'JACSW350 Music Musicology',
  'JACSC220 Botany Mycology',
  'GLI004 Government Led Initiatives NPIF',
  'GLI006 Government Led Initiatives NPIF Innovation Fellowships',
  'GLI007 Government Led Initiatives NPIF Innovation Interface Fellowships',
  'GLI008 Government Led Initiatives NPIF Studentship',
  'GLI005 Government Led Initiatives NPIF Training Award',
  'CSES0000300006 RCUK Programmes Nanoscience',
  'JACSL214 Political Theories Nationalism',
  'JACSH500 Engineering Naval Architecture',
  'JACSH590 Naval Architecture Naval Architecture not elsewhere classified',
  'JACSW711 Fabric and Leather Crafts Needlecraft',
  'GLI026 Government Led Initiatives Netherlands',
  'JACSG420 Computer Science Networks and Communications',
  'JACSG730 Artificial Intelligence Neural Computing',
  'JACSC860 Psychology Neuropsychology',
  'JACSB140 Subjects allied to Medicine Neuroscience',
  'GLI032 Government Led Initiatives New Zealand',
  'JACSV262 Australasian History New Zealand History',
  'CSES0000300009 RCUK Programmes Newton',
  'JACSV251 African History North African History',
  'JACSM113 UK Legal Systems Northern Irish Law',
  'JACSR612 Scandinavian Languages Norwegian Language',
  'JACSR622 Scandinavian Literature Norwegian Literature',
  'JACSR632 Scandinavian Society and Culture Norwegian Society and Culture',
  'JACSH821 Atomic Engineering Nuclear Engineering',
  'JACSF370 Physics Nuclear and Particle Physics',
  'JACSG140 Mathematics Numerical Analysis',
  'JACSB700 Subjects allied to Medicine Nursing',
  'JACSB790 Nursing Nursing not elsewhere classified',
  'JACSB400 Subjects allied to Medicine Nutrition',
  'JACSB490 Nutrition Nutrition not elsewhere classified',
  'GLI1 Government Led Initiatives ODA Commitment',
  'JACSG622 Programming Object Oriented Programming',
  'JACSB920 Others in Subjects allied to Medicine Occupational Health',
  'JACSC811 Applied Psychology Occupational Psychology',
  'JACSB930 Others in Subjects allied to Medicine Occupational Therapy',
  'JACSF700 Physical Sciences Ocean Sciences',
  'JACSF790 Ocean Sciences Ocean Sciences not elsewhere classified',
  'JACSN710 Office skills Office Administration',
  'JACSJ941 Machinery Maintenance Office Machinery Maintenance',
  'JACSN700 Business and Administrative studies Office skills',
  'JACSN790 Office skills Office skills not elsewhere classified',
  'JACSJ521 Printing Offset Lithography',
  'JACSH350 Mechanical Engineering Offshore Engineering',
  'JACSL224 Political Systems Oligarchy',
  'JACSG412 Computer Architectures & Operating Systems Operating Systems',
  'JACSG200 Mathematical and Computer Sciences Operational Research',
  'JACSG290 Operational Research Operational Research not elsewhere classified',
  'JACSB500 Subjects allied to Medicine Ophthalmics',
  'JACSB590 Ophthalmics Ophthalmics not elsewhere classified',
  'JACSF360 Physics Optical Physics',
  'JACSH680 Electronic and Electrical Engineering Optoelectronic Engineering',
  'JACSB510 Ophthalmics Optometry',
  'JACSV322 Social History Oral History',
  'JACSD461 Organic Farming Organic Arable and Fruit Farming',
  'JACSF160 Chemistry Organic Chemistry',
  'JACSD460 Agriculture Organic Farming',
  'JACSD463 Organic Farming Organic Fish Farming',
  'JACSD530 Forestry Organic Forestry',
  'JACSD462 Organic Farming Organic Livestock',
  'JACSN215 Management Techniques Organisational Development',
  'JACSF161 Organic Chemistry Organometallic Chemistry',
  'JACSW782 Paper Crafts Origami',
  'JACSD434 Fish Farming Ornamental Fish',
  'JACSB520 Ophthalmics Orthoptics',
  'JACSB310 Complementary Medicine Osteopathy',
  'JACST410 Other Asian studies Other Asian Language studies',
  'JACST420 Other Asian studies Other Asian Literature studies',
  'JACSV626 Religious studies Other Asian Religious studies',
  'JACST430 Other Asian studies Other Asian Society and Culture studies',
  'JACST400 Eastern, Asiatic, African, American and Australasian Languages, Literature and related subjects Other Asian studies',
  'JACST490 Other Asian studies Other Asian studies not elsewhere classified',
  'JACSR910 Others in European Languages, Literature and related subjects Other European Languages',
  'JACSR920 Others in European Languages, Literature and related subjects Other European Literature',
  'JACSR930 Others in European Languages, Literature and related subjects Other European Societies and Cultures',
  'JACSK900 Architecture, Building and Planning Others in Architecture, Building and Planning',
  'JACSC900 Biological Sciences Others in Biological Sciences',
  'JACSN900 Business and Administrative studies Others in Business and Administrative studies',
  'JACSG920 Others in Mathematical and Computing Sciences Others in Computing Sciences',
  'JACSW900 Creative Arts and Design Others in Creative Arts and Design',
  'JACST910 Others in Eastern, Asiatic, African, American and Australasian Languages, Literature and related subjects Others in Eastern, Asiatic, African, American and Australasian Languages',
  'JACST900 Eastern, Asiatic, African, American and Australasian Languages, Literature and related subjects Others in Eastern, Asiatic, African, American and Australasian Languages, Literature and related subjects',
  'JACST920 Others in Eastern, Asiatic, African, American and Australasian Languages, Literature and related subjects Others in Eastern, Asiatic, African, American and Australasian Literature',
  'JACST930 Others in Eastern, Asiatic, African, American and Australasian Languages, Literature and related subjects Others in Eastern, Asiatic, African, American and Australasian Societies and Cultures',
  'JACSX900 Education Others in Education',
  'JACSH900 Engineering Others in Engineering',
  'JACSR900 European Languages, Literature and related subjects Others in European Languages, Literature and related subjects',
  'JACSV900 Historical and Philosophical studies Others in Historical and Philosophical studies',
  'JACSM900 Law Others in Law',
  'JACSQ900 Linguistics, Classics and related subjects Others in Linguistics, Classics and related subjects',
  'JACSP900 Mass Communications and Documentation Others in Mass Communications and Documentation',
  'JACSG910 Others in Mathematical and Computing Sciences Others in Mathematical Sciences',
  'JACSG900 Mathematical and Computer Sciences Others in Mathematical and Computing Sciences',
  'JACSA900 Medicine and Dentistry Others in Medicine and Dentistry',
  'JACSF900 Physical Sciences Others in Physical Sciences',
  'JACSL900 Social studies Others in Social studies',
  'JACSB900 Subjects allied to Medicine Others in Subjects allied to Medicine',
  'JACSJ900 Technologies Others in Technology',
  'JACSD900 Veterinary Sciences, Agriculture and related subjects Others in Veterinary Sciences, Agriculture and related subjects',
  'JACSD340 Animal Science Overseas Veterinary Development',
  'JACSB730 Nursing Paediatric Nursing',
  'JACSW120 Fine Art Painting',
  'JACSF641 Earth Science Palaeontology',
  'JACSB701 Nursing Palliative Care Nursing',
  'JACSW780 Crafts Paper Crafts',
  'JACSJ512 Materials Technology Paper Technology',
  'JACSP305 Media studies Paper-based Media studies',
  'JACSB780 Nursing Paramedical Nursing',
  'JACSC111 Biology Parasitology',
  'JACSV650 Theology and Religious studies Pastoral studies',
  'JACSB132 Pathology Pathobiology',
  'JACSB130 Anatomy, Physiology and Pathology Pathology',
  'JACSJ443 Clothing Production Pattern Cutting',
  'JACSJ221 Metallic Fabrication Pattern Making',
  'JACSH232 Transport Engineering Pavement Engineering',
  'JACSH231 Transport Engineering Permanent Way Engineering',
  'JACSC360 Zoology Pest Science',
  'JACSF164 Organic Chemistry Petrochemical Chemistry',
  'JACSJ160 Minerals Technology Petrochemical Technology',
  'JACSH850 Chemical, Process and Energy Engineering Petroleum Engineering',
  'JACSF151 Medicinal Chemistry Pharmaceutical Chemistry',
  'JACSH812 Chemical Engineering Pharmaceutical Engineering',
  'JACSB210 Pharmacology, Toxicology and Pharmacy Pharmacology',
  'JACSB200 Subjects allied to Medicine Pharmacology, Toxicology and Pharmacy',
  'JACSB290 Pharmacology, Toxicology and Pharmacy Pharmacology, Toxicology and Pharmacy not elsewhere classified',
  'JACSB230 Pharmacology, Toxicology and Pharmacy Pharmacy',
  'JACSV500 Historical and Philosophical studies Philosophy',
  'JACSV590 Philosophy Philosophy not elsewhere classified',
  'JACSV550 Philosophy Philosophy of Science',
  'JACSQ131 Phonetics and Phonology Phonetics',
  'JACSQ130 Linguistics Phonetics and Phonology',
  'JACSQ132 Phonetics and Phonology Phonology',
  'JACSJ522 Printing Photo-Lithography',
  'JACSW640 Cinematics and Photography Photography',
  'JACSF170 Chemistry Physical Chemistry',
  'JACSF840 Physical and Terrestrial Geographical and Environmental Sciences Physical Geography',
  'JACSF Reporting - JACS Physical Sciences',
  'JACSF990 Others in Physical Sciences Physical Sciences not elsewhere classified',
  'JACSL620 Anthropology Physical and Biological Anthropology',
  'JACSF800 Physical Sciences Physical and Terrestrial Geographical and Environmental Sciences',
  'JACSF300 Physical Sciences Physics',
  'JACSF390 Physics Physics not elsewhere classified',
  'JACSB120 Anatomy, Physiology and Pathology Physiology',
  'JACSB160 Subjects allied to Medicine Physiotherapy',
  'JACSF522 Space and Planetary Sciences Planetary Science',
  'JACSK400 Architecture, Building and Planning Planning (Urban, Rural and Regional)',
  'JACSK490 Planning (Urban, Rural and Regional) Planning (Urban, Rural and Regional) not elsewhere classified',
  'JACSK430 Planning (Urban, Rural and Regional) Planning studies',
  'JACSC750 Molecular Biology, Biophysics and Biochemistry Plant Biochemistry',
  'JACSC230 Botany Plant Biotechnology',
  'JACSC240 Botany Plant Cell Science',
  'JACSC250 Botany Plant Pathology',
  'JACSJ411 Polymers Technology Plastics',
  'JACSL223 Political Systems Plutocracy',
  'JACSW820 Imaginative Writing Poetry Writing',
  'JACSR712 Russian and East European Languages Polish Language',
  'JACSR722 Russian and East European Literature Polish Literature',
  'JACSR732 Russian and East European Society and Culture Polish Society and Culture',
  'JACSL150 Economics Political Economics',
  'JACSL723 Human and Social Geography by topic Political Geography',
  'JACSL380 Sociology Political Sociology',
  'JACSL220 Politics Political Systems',
  'JACSL210 Politics Political Theories',
  'NABS111 Reporting - NABS Political and social systems, structures and processes  ',
  'JACSL200 Social studies Politics',
  'JACSL290 Politics Politics not elsewhere classified',
  'JACSL243 International Politics Politics of a specific country/region',
  'JACSF853 Environmental Sciences Pollution Control',
  'JACSF162 Organic Chemistry Polymer Chemistry',
  'JACSJ410 Polymers and Textiles Polymers Technology',
  'JACSJ400 Technologies Polymers and Textiles',
  'JACSJ490 Polymers and Textiles Polymers and Textiles not elsewhere classified',
  'JACSC170 Biology Population Biology',
  'JACSR510 Portuguese studies Portuguese Language',
  'JACSR511 Portuguese studies Portuguese Languages in other countries',
  'JACSR520 Portuguese studies Portuguese Literature',
  'JACSR530 Portuguese studies Portuguese Society and Culture',
  'JACSR500 European Languages, Literature and related subjects Portuguese studies',
  'JACSR590 Portuguese studies Portuguese studies not elsewhere classified',
  'JACSW751 Clay and Stone Crafts Pottery',
  'JACSD423 Livestock Poultry keeping',
  'JACSB714 Community Nursing Practice Nursing',
  'JACSQ460 Ancient Language studies Prakrit',
  'JACSA200 Medicine and Dentistry Pre-clinical Dentistry',
  'JACSA100 Medicine and Dentistry Pre-clinical Medicine',
  'JACSD100 Veterinary Sciences, Agriculture and related subjects Pre-clinical Veterinary Medicine',
  'JACSD190 Pre-clinical Veterinary Medicine Pre-clinical Veterinary Medicine not elsewhere classified',
  'JACSJ520 Materials Technology not otherwise specified Printing',
  'JACSW140 Fine Art Printmaking',
  'JACSM220 Law by Topic Private Law',
  'EUC6 EU Classifications Prizes',
  'JACSG320 Statistics Probability',
  'JACSL560 Social Work Probation/After Care',
  'JACSG621 Programming Procedural Programming',
  'JACSW612 Moving Image Techniques Producing Motion Pictures',
  'JACSW430 Drama Producing for Theatre',
  'JACSH713 Manufacturing Systems Engineering Production Processes',
  'JACSH700 Engineering Production and Manufacturing Engineering',
  'JACSH790 Production and Manufacturing Engineering Production and Manufacturing Engineering not elsewhere classified',
  'JACSG620 Software Engineering Programming',
  'JACSN213 Management Techniques Project Management',
  'JACSN560 Marketing Promotion and Advertising',
  'JACSM223 Private Law Property Law',
  'JACSN232 Land and property management Property Management',
  'JACSH450 Aerospace Engineering Propulsion Systems',
  'JACSW830 Imaginative Writing Prose Writing',
  'JACSQ150 Linguistics Psycholinguistics',
  'JACSC800 Biological Sciences Psychology',
  'JACSC890 Psychology Psychology not elsewhere classified',
  'JACSC870 Psychology Psychometrics',
  'JACSN412 Accountancy Public Accountancy',
  'JACSL231 UK Government/Parliamentary Studies Public Administration',
  'JACSH123 Safety Engineering Public Health Engineering',
  'JACSM130 Law by area Public International Law',
  'JACSM210 Law by Topic Public Law',
  'JACSL430 Social Policy Public Policy',
  'JACSP210 Publicity studies Public Relations',
  'JACSP200 Mass Communications and Documentation Publicity studies',
  'JACSP290 Publicity studies Publicity studies not elsewhere classified',
  'JACSP400 Mass Communications and Documentation Publishing',
  'JACSP490 Publishing Publishing not elsewhere classified',
  'JACSP412 Electronic Publishing Publishing on CD-ROM',
  'JACSP411 Electronic Publishing Publishing on audio/video tape',
  'JACSP413 Electronic Publishing Publishing via the World Wide Web',
  'JACSG110 Mathematics Pure Mathematics',
  'JACSH720 Production and Manufacturing Engineering Quality Assurance Engineering',
  'JACSK240 Building Quantity Surveying',
  'JACSF342 Mathematical & Theoretical Physics Quantum Mechanics',
  'JACSJ120 Minerals Technology Quarrying',
  'JACSF643 Earth Science Quaternary studies',
  'NABS124 General advancement of knowledge: R&D financed from General University Funds (GUF) R&D related to Agricultural Sciences - financed from GUF',
  'NABS134 General advancement of knowledge: R&D financed from other sources than GUF R&D related to Agricultural Sciences - financed from other sources than GUF',
  'NABS122 General advancement of knowledge: R&D financed from General University Funds (GUF) R&D related to Engineering Sciences - financed from GUF',
  'NABS132 General advancement of knowledge: R&D financed from other sources than GUF R&D related to Engineering Sciences - financed from other sources than GUF',
  'NABS126 General advancement of knowledge: R&D financed from General University Funds (GUF) R&D related to Humanities - financed from GUF',
  'NABS136 General advancement of knowledge: R&D financed from other sources than GUF R&D related to Humanities - financed from other sources than GUF',
  'NABS123 General advancement of knowledge: R&D financed from General University Funds (GUF) R&D related to Medical Sciences - financed from GUF',
  'NABS133 General advancement of knowledge: R&D financed from other sources than GUF R&D related to Medical Sciences - financed from other sources than GUF',
  'NABS121 General advancement of knowledge: R&D financed from General University Funds (GUF) R&D related to Natural Sciences - financed from GUF  ',
  'NABS131 General advancement of knowledge: R&D financed from other sources than GUF R&D related to Natural Sciences - financed from other sources than GUF',
  'NABS125 General advancement of knowledge: R&D financed from General University Funds (GUF) R&D related to Social Sciences - financed from GUF',
  'NABS135 General advancement of knowledge: R&D financed from other sources than GUF R&D related to Social Sciences - financed from other sources than GUF',
  'CSES003  RCUK Programmes',
  'JACSF351 Medical Physics Radiation Physics',
  'JACSP312 Media Production Radio Production',
  'JACSP302 Media studies Radio studies',
  'JACSB821 Radiology Radiography, diagnostic',
  'JACSB822 Radiology Radiography, therapeutic',
  'JACSB820 Medical Technology Radiology',
  'JACSH332 Automotive Engineering Rail Vehicle Engineering',
  'JACSN222 Institutional Management Recreation/Leisure Management',
  'JACSN614 Unknown Listing in JACS Recruitment Methods',
  'GCA4 GCRF Challenge Areas Reduce conflict and promote peace, justice and humanitarian action',
  'GCA5 GCRF Challenge Areas Reduce poverty and inequality, including gender inequalities',
  'JACSW760 Crafts Reed Crafts',
  'JACSB346 Alternative Medicine Reflexology',
  'JACSK410 Planning (Urban, Rural and Regional) Regional Planning',
  'JACSL350 Sociology Religion in Society',
  'JACSV620 Theology and Religious studies Religious studies',
  'JACSV640 Theology and Religious studies Religious writings',
  'JACSF832 Topography Remote Sensing',
  'FRAS  Reporting - FRASCATI',
  'JACS  Reporting - JACS',
  'NABS  Reporting - NABS',
  'JACSC142 Developmental/Reproductive Biology Reproductive Biology',
  'JACSJ523 Printing Reprographic Techniques',
  'EUC1 EU Classifications Research and Innovation Actions',
  'JACSX200 Education Research and Study Skills in Education',
  'JACSX290 Research and Study Skills in Education Research and Study skills not elsewhere classified',
  'JACSX210 Research and Study Skills in Education Research skills',
  'GCA6 GCRF Challenge Areas Resilience and action on short-term environmental shocks and long-term environmental change',
  'JACSN240 Management studies Retail Management',
  'JACSH331 Automotive Engineering Road Vehicle Engineering',
  'JACSH671 Robotics and Cybernetics Robotics',
  'JACSH670 Electronic and Electrical Engineering Robotics and Cybernetics',
  'JACSJ130 Minerals Technology Rock Mechanics',
  'JACSD440 Agriculture Rural Estate Management',
  'JACSK422 Urban and Rural Planning Rural Planning',
  'JACSV225 European History Russian History',
  'JACSR711 Russian and East European Languages Russian Language',
  'JACSQ175 Linguistics of non-English European Languages Russian Linguistics',
  'JACSR721 Russian and East European Literature Russian Literature',
  'JACSR731 Russian and East European Society and Culture Russian Society and Culture',
  'JACSR710 Russian and East European studies Russian and East European Languages',
  'JACSR720 Russian and East European studies Russian and East European Literature',
  'JACSR730 Russian and East European studies Russian and East European Society and Culture',
  'JACSR700 European Languages, Literature and related subjects Russian and East European studies',
  'JACSR790 Russian and East European studies Russian and East European studies not elsewhere classified',
  'GLI002 Government Led Initiatives Rutherford Fellowships',
  'EUC3 EU Classifications SME Instrument',
  'GLI010 Government Led Initiatives SPF (Strategic Priorities Fund)',
  'JACSH120 General Engineering Safety Engineering',
  'JACSN520 Marketing Sales Management',
  'JACSD433 Fish Farming Saltwater Fish',
  'JACSQ450 Ancient Language studies Sanskrit',
  'JACSH643 Communications Engineering Satellite Engineering',
  'JACSR610 Scandinavian studies Scandinavian Languages',
  'JACSR620 Scandinavian studies Scandinavian Literature',
  'JACSR630 Scandinavian studies Scandinavian Society and Culture',
  'JACSR600 European Languages, Literature and related subjects Scandinavian studies',
  'JACSR690 Scandinavian studies Scandinavian studies not elsewhere classified',
  'JACSV530 Philosophy Scholastic Philosophy',
  'JACSB713 Community Nursing School Nursing',
  'JACSQ530 Celtic studies Scottish Gaelic',
  'JACSQ531 Scottish Gaelic Scottish Gaelic Literature',
  'JACSV212 British History Scottish History',
  'JACSM114 UK Legal Systems Scottish Law',
  'JACSJ524 Printing Screen Process Printing',
  'JACSW810 Imaginative Writing Scriptwriting',
  'JACSW130 Fine Art Sculpture',
  'JACSN852 Transport Studies Sea Travel',
  'JACSN720 Office skills Secretarial and Typing skills',
  'GCA7 GCRF Challenge Areas Secure and resilient food systems supported by sustainable marine resources and agriculture',
  'JACSL435 Public Policy Security Policy',
  'JACSC570 Microbiology Serology',
  'JACSH520 Naval Architecture Ship Design',
  'JACSH333 Automotive Engineering Ship Propulsion Engineering',
  'JACSH510 Naval Architecture Shipbuilding',
  'JACSN722 Secretarial and Typing skills Shorthand and Shorthand Transcription',
  'JACSW721 Metal Crafts Silversmithing/Goldsmithing',
  'GLI027 Government Led Initiatives Singapore',
  'JACSL371 Social Theory Social Hierarchy',
  'JACSV320 History by topic Social History',
  'JACSV540 Philosophy Social Philosophy',
  'JACSL400 Social studies Social Policy',
  'JACSL490 Social Policy Social Policy not elsewhere classified',
  'JACSC880 Psychology Social Psychology',
  'JACSL370 Sociology Social Theory',
  'JACSL500 Social studies Social Work',
  'JACSL590 Social Work Social Work not elsewhere classified',
  'JACSL610 Anthropology Social and Cultural Anthropology',
  'JACSL Reporting - JACS Social studies',
  'JACSL990 Others in Social studies Social studies not elsewhere classified',
  'JACSL213 Political Theories Socialism',
  'JACSL360 Sociology Socio-economics',
  'JACSQ140 Linguistics Sociolinguistics',
  'JACSL300 Social studies Sociology',
  'JACSL390 Sociology Sociology not elsewhere classified',
  'JACSL391 Sociology not elsewhere classified Sociology of Science and Technology',
  'JACSW713 Fabric and Leather Crafts Soft Furnishing',
  'JACSG610 Software Engineering Software Design',
  'JACSG600 Mathematical and Computer Sciences Software Engineering',
  'JACSG690 Software Engineering Software Engineering not elsewhere classified',
  'JACSF870 Physical and Terrestrial Geographical and Environmental Sciences Soil Science',
  'JACSD750 Agricultural Sciences Soil as an Agricultural medium',
  'JACSH142 Mechanics Solid Mechanics',
  'JACSF321 Chemical Physics Solid state Physics',
  'JACSV233 American History South American History',
  'JACST310 South Asian studies South Asian Language studies',
  'JACST320 South Asian studies South Asian Literature studies',
  'JACST330 South Asian studies South Asian Society and Culture studies',
  'JACST300 Eastern, Asiatic, African, American and Australasian Languages, Literature and related subjects South Asian studies',
  'JACST390 South Asian studies South Asian studies not elsewhere classified',
  'JACSV243 Asian History South East Asian History',
  'GLI021 Government Led Initiatives South Korea',
  'JACSV253 African History Southern African History',
  'JACSF521 Space and Planetary Sciences Space Science',
  'JACSF520 Astronomy Space and Planetary Sciences',
  'JACSR410 Spanish studies Spanish Language',
  'JACSR411 Spanish Language Spanish Languages in other countries',
  'JACSQ174 Linguistics of non-English European Languages Spanish Linguistics',
  'JACSR420 Spanish studies Spanish Literature',
  'JACSR430 Spanish studies Spanish Society and Culture',
  'JACSR400 European Languages, Literature and related subjects Spanish studies',
  'JACSR490 Spanish studies Spanish studies not elsewhere classified',
  'JACSB620 Aural and Oral Sciences Speech Science',
  'JACSG710 Artificial Intelligence Speech and Natural Language Processing',
  'JACSN563 Promotion and Advertising Sponsorship',
  'JACSC600 Biological Sciences Sports Science',
  'JACSN612 Unknown Listing in JACS Staff Development',
  'JACSW461 Theatre Design Stage Design',
  'JACSW450 Drama Stage Management',
  'JACSG340 Statistics Statistical Modelling',
  'JACSG300 Mathematical and Computer Sciences Statistics',
  'JACSG390 Statistics Statistics not elsewhere classified',
  'JACSG330 Statistics Stochastic Processes',
  'JACSV420 Archaeology Stone Age',
  'JACSW753 Clay and Stone Crafts Stone Crafts',
  'JACSN211 Management Techniques Strategic Management',
  'JACSL251 International Relations Strategic studies',
  'JACSF130 Chemistry Structural Chemistry',
  'JACSH210 Civil Engineering Structural Engineering',
  'JACSH143 Mechanics Structural Mechanics',
  'JACSX220 Research and Study Skills in Education Study skills',
  'JACSB990 Others in Subjects allied to Medicine Subjects Allied to Medicine not elsewhere classified',
  'JACSB Reporting - JACS Subjects allied to Medicine',
  'JACSH514 Shipbuilding Submarine Building',
  'JACSH524 Ship Design Submarine Design',
  'JACSQ440 Ancient Language studies Sumerian',
  'JACSH513 Shipbuilding Surface Combat Ship Building',
  'JACSH523 Ship Design Surface Combat Ship Design',
  'JACSW740 Crafts Surface Decoration',
  'JACSH512 Shipbuilding Surface Freight Ship Building',
  'JACSH522 Ship Design Surface Freight Ship Design',
  'JACSH511 Shipbuilding Surface Passenger Ship Building',
  'JACSH521 Ship Design Surface Passenger Ship Design',
  'JACSH240 Civil Engineering Surveying Science',
  'GCA8 GCRF Challenge Areas Sustainable cities and communities',
  'GCA9 GCRF Challenge Areas Sustainable health and well being',
  'GCA10 GCRF Challenge Areas Sustainable livelihoods supported by strong foundations for inclusive economic growth and innovation',
  'GCA11 GCRF Challenge Areas Sustainable production and consumption of materials and other resources',
  'JACSR611 Scandinavian Languages Swedish Language',
  'JACSR621 Scandinavian Literature Swedish Literature',
  'JACSR631 Scandinavian Society and Culture Swedish Society and Culture',
  'GLI022 Government Led Initiatives Switzerland',
  'JACSG530 Information Systems Systems Analysis and Design',
  'JACSG590 Information Systems Systems Analysis and Design not elsewhere classified',
  'JACSG550 Information Systems Systems Auditing',
  'JACSG520 Information Systems Systems Design Methodologies',
  'JACSH650 Electronic and Electrical Engineering Systems Engineering',
  '3PTY00001 3rd Party Involvement TSB',
  'GLI028 Government Led Initiatives Taiwan',
  'JACSJ431 Leather Technology Tanning',
  'JACSN330 Finance Taxation',
  'JACSX162 Training Teachers - Specialist Teaching English as a Foreign Language (TEFL)',
  'JACSJ Reporting - JACS Technologies',
  'JACSJ990 Others in Technology Technologies not elsewhere classified',
  'JACSH641 Communications Engineering Telecommunications Engineering',
  'JACSP311 Media Production Television Production',
  'JACSP301 Media studies Television studies',
  'JACSJ421 Textiles Technology Textile Chemistry',
  'JACSW231 Clothing/Fashion Design Textile Design',
  'JACSJ420 Polymers and Textiles Textiles Technology',
  'JACSW762 Reed Crafts Thatching',
  'JACSV641 Religious writings The Bible and Christian texts',
  "JACSV642 Religious writings The Qu'ran and Islamic texts",
  'JACSV643 Religious writings The Torah and Judaic texts',
  'JACSW460 Drama Theatre Design',
  'JACSW440 Drama Theatre studies',
  'JACSW452 Stage Management Theatrical Make-up',
  'JACSW451 Stage Management Theatrical Wardrobe Design',
  'JACSV610 Theology and Religious studies Theology',
  'JACSV600 Historical and Philosophical studies Theology and Religious studies',
  'JACSV690 Theology and Religious studies Theology and Religious studies not elsewhere classified',
  'JACSH311 Dynamics Thermodynamics',
  'JACSW752 Clay and Stone Crafts Tile Making',
  'JACSD516 Trees and Shrubs Timber Production',
  'JACSF830 Physical and Terrestrial Geographical and Environmental Sciences Topography',
  'JACSM224 Private Law Torts',
  'JACSN800 Business and Administrative studies Tourism, Transport and Travel',
  'JACSN890 Tourism, Transport and Travel Tourism, Transport and Travel not elsewhere classified',
  'JACSB220 Pharmacology, Toxicology and Pharmacy Toxicology',
  'JACSN613 Unknown Listing in JACS Training Methods',
  'JACSX100 Education Training Teachers',
  'JACSX131 Training Teachers - Secondary Training Teachers - (key stage 3)',
  'JACSX132 Training Teachers - Secondary Training Teachers - (key stage 4)',
  'JACSX150 Training Teachers Training Teachers - Adult Education',
  'JACSX151 Training Teachers - Adult Education Training Teachers - Coaching',
  'JACSX141 Training Teachers - Tertiary Training Teachers - Further Education',
  'JACSX142 Training Teachers - Tertiary Training Teachers - Higher Education',
  'JACSX121 Training Teachers - Primary Training Teachers - Infant (key stage 1)',
  'JACSX122 Training Teachers - Primary Training Teachers - Junior (key stage 2)',
  'JACSX110 Training Teachers Training Teachers - Nursery',
  'JACSX120 Training Teachers Training Teachers - Primary',
  'JACSX130 Training Teachers Training Teachers - Secondary',
  'JACSX161 Training Teachers - Specialist Training Teachers - Special Needs',
  'JACSX160 Training Teachers Training Teachers - Specialist',
  'JACSX140 Training Teachers Training Teachers - Tertiary',
  'JACSX190 Training Teachers Training Teachers not elsewhere classified',
  'JACSQ910 Others in Linguistics, Classics and related subjects Translation studies',
  'JACSQ920 Others in Linguistics, Classics and related subjects Translation theory',
  'JACSH230 Civil Engineering Transport Engineering',
  'JACSL724 Human and Social Geography by topic Transport Geography',
  'JACSJ960 Others in Technology Transport Logistics',
  'JACSK460 Planning (Urban, Rural and Regional) Transport Planning',
  'JACSL434 Public Policy Transport Policy',
  'JACSN850 Tourism, Transport and Travel Transport Studies',
  'NABS104 Reporting - NABS Transport, telecommunication and other infrastructures  ',
  'JACSN810 Tourism, Transport and Travel Travel Management',
  'JACSD513 Trees and Shrubs Tree Nutrition',
  'JACSD512 Trees and Shrubs Tree Physiology',
  'JACSD515 Trees and Shrubs Tree Production',
  'JACSD514 Trees and Shrubs Tree Protection',
  'JACSD510 Forestry Trees and Shrubs',
  'JACSH321 Mechanisms and Machines Turbine Technology',
  'JACSW540 Dance Types of Dance',
  'JACSW340 Music Types of Music',
  'JACSW211 Graphic Design Typography',
  'JACSL232 UK Government/Parliamentary Studies UK Constitutional studies',
  'JACSL230 Politics UK Government/Parliamentary Studies',
  'JACSM110 Law by area UK Legal Systems',
  'JACSL410 Social Policy UK Social Policy',
  'JACSN830 Tourism, Transport and Travel UK Tourism',
  'GLI023 Government Led Initiatives USA',
  'JACSV232 American History USA History',
  'GCA12 GCRF Challenge Areas Understand and respond effectively to forced displacement and multiple refugee crises',
  'JACSN610 Human Resource Management Unknown Listing in JACS',
  'JACSK421 Urban and Rural Planning Urban Planning',
  'JACSL722 Human and Social Geography by topic Urban Geography',
  'JACSK420 Planning (Urban, Rural and Regional) Urban and Rural Planning',
  'JACSK440 Planning (Urban, Rural and Regional) Urban studies',
  'JACSN234 Land and property management Valuation and Auctioneering',
  'JACSD613 Food Science Vegetable Science',
  'JACSW734 Wood Crafts Veneering',
  'JACSC742 Medical and Veterinary Biochemistry Veterinary Biochemistry',
  'JACSC432 Medical and Veterinary Genetics Veterinary Genetics',
  'JACSC522 Medical and Veterinary Microbiology Veterinary Microbiology',
  'JACSD310 Animal Science Veterinary Nursing',
  'JACSD330 Animal Science Veterinary Public Health',
  'JACSD390 Animal Science Veterinary Sciences not elsewhere classified',
  'JACSD Reporting - JACS Veterinary Sciences, Agriculture and related subjects',
  'JACSD990 Others in Veterinary Sciences, Agriculture and related subjects Veterinary Sciences, Agriculture and related subjects not elsewhere classified',
  'JACSH342 Acoustics and Vibration Vibration',
  'JACSC540 Microbiology Virology',
  'JACSH674 Robotics and Cybernetics Virtual Reality Engineering',
  'JACSW213 Graphic Design Visual Communication',
  'JACSW614 Moving Image Techniques Visual and Audio Effects',
  'JACSL252 International Relations War & Peace studies',
  'JACSH122 Safety Engineering Water Quality Control',
  'JACSD443 Rural Estate Management Water Resource Management',
  'JACSW714 Fabric and Leather Crafts Weaving',
  'JACSL432 Public Policy Welfare Policy',
  'JACSQ560 Celtic studies Welsh',
  'JACSV213 British History Welsh History',
  'JACSM112 UK Legal Systems Welsh Law',
  'JACSQ561 Welsh Welsh Literature',
  'JACSV255 African History West African History',
  'JACSD446 Rural Estate Management Wilderness Management',
  "JACSL321 Gender studies Women's Studies",
  'JACSW730 Crafts Wood Crafts',
  'JACSV270 History by area World History',
  'JACSL530 Social Work Youth Work',
  'JACSC300 Biological Sciences Zoology',
  'JACSC390 Zoology Zoology not elsewhere classified',
];
export const reportingTags = reportingData;

let routingData = [
  { council: 'MRC', name: 'NMHB' },
  { council: 'MRC', name: 'DPFS/DCS/BMC' },
  { council: 'MRC', name: 'BMBR' },
  { council: 'MRC', name: 'NPRI' },
  { council: 'MRC', name: 'PHIND' },
  { council: 'MRC', name: 'RMRC' },
  { council: 'MRC', name: 'Newton Fund' },
  { council: 'MRC', name: 'Trials' },
  { council: 'STFC', name: 'Astronomy Grants Panel: Astronomy Solar Studies' },
  { council: 'STFC', name: 'Astronomy Grants Panel: Astronomy Planetary' },
  { council: 'STFC', name: 'Other' },
  { council: 'STFC', name: 'Particle Astrophysics' },
  { council: 'STFC', name: 'PPGP (Experiment)' },
  { council: 'STFC', name: 'PPGP (HPC)' },
  { council: 'STFC', name: 'PPGP (Theory)' },
  { council: 'STFC', name: 'Science (Board)' },
  { council: 'STFC', name: 'Space Missions/Ground Based Facilities' },
  { council: 'STFC', name: 'Nuclear Physics Panel' },
  { council: 'STFC', name: 'Nuclear Physics Project Peer Review Panel' },
  { council: 'STFC', name: 'Particle Physics IPPP Panel' },
  { council: 'STFC', name: 'Nuclear Physics Project Peer Review Panel' },
  { council: 'STFC', name: 'Accelerator Peer Review Panel' },
  { council: 'STFC', name: 'Project Peer Review Panel (PP)' },
  { council: 'BBSRC', name: 'Committee A' },
  { council: 'BBSRC', name: 'Committee B' },
  { council: 'BBSRC', name: 'Committee C' },
  { council: 'BBSRC', name: 'committee D' },
];
export const allRoutingData = routingData;

let qualifiers = [
  'Q137 Time Period 18th Century',
  'Q138 Time Period 19th Century',
  'Q139 Time Period 20th Century',
  'Q172 Project Engagement by Sector Academic Users',
  'Q8 Public Engagement Audience Adult spec. interest/lifestyle',
  'Q7 Public Engagement Audience Adults by occupation',
  'Q221 Health categories Aetiology',
  'Q195 Collaboration location region Africa',
  'Q154 Geographic Area Africa',
  'Q61 Use of Facilities Analytical Electron Microscopy',
  'Q123 Time Period Ancient Near East: Prehistory',
  'QP8  Approach',
  'Q126 Time Period Archaic Greece: c. 850-600BC',
  'Q229 Geographic Area Arctic Ocean',
  'Q39 Public Engagement Methodology Art or music',
  'Q230 Geographic Area Atlantic Ocean',
  'Q72 Use of Facilities Atom Probe Facility',
  'Q42 Public Engagement Methodology Attitude study',
  'Q17 Public Engagement Audience Audiences for diversity',
  'Q200 Health categories Blood',
  'Q177 Project Engagement by Sector Business Sector',
  'Q132 Time Period Byzantine Empire',
  'Q201 Health categories Cancer',
  'Q114 Materials Carbon-based materials',
  'Q202 Health categories Cardiovascular',
  'Q104 Materials Cement and Concrete',
  'Q152 Geographic Area Central America inc Caribbean',
  'Q193 Collaboration location region Central America inc Caribbean',
  'Q56 Use of Facilities Central Laser Facility',
  'Q180 Project Engagement by Sector Central and Local Government',
  'Q58 Use of Facilities Chemical Database Facility',
  'Q127 Time Period Classical Greece: c. 500BC',
  'Q43 Public Engagement Methodology Classroom activity',
  'QP10  Collaboration location region',
  'Q27 Public Engagement Methodology Competition',
  'Q105 Materials Composites',
  'Q203 Health categories Congenital Disorders',
  'Q40 Public Engagement Methodology Consultation',
  'Q140 Time Period Contemporary',
  'Q65 Use of Facilities Dark Fibre Infrastruct. Serv.',
  'Q29 Public Engagement Methodology Demonstration show',
  'Q47 Use of Facilities Diamond',
  'Q68 Use of Facilities EPR Spectroscopy Service',
  'Q50 Use of Facilities ESRF',
  'Q204 Health categories Ear',
  'Q133 Time Period Early Medieval: c.400 - 1100',
  'Q135 Time Period Early Modern: c.1500 - 1800',
  'Q147 Geographic Area Eastern Europe',
  'Q188 Collaboration location region Eastern Europe',
  'Q120 Time Period Egyption Prehistory',
  'Q60 Use of Facilities Engineering Loan Pool',
  'Q143 Geographic Area England',
  'Q184 Collaboration location region England',
  'Q220 Health categories Epidemiology',
  'Q69 Use of Facilities Epitaxy Service',
  'Q24 Public Engagement Methodology Exhibition',
  'Q165 Approach Experimental',
  'Q169 Approach Exploit. of existing datasets',
  'Q205 Health categories Eye',
  'Q66 Use of Facilities FELIX',
  'Q9 Public Engagement Audience Families',
  'Q197 Collaboration location region Far East (China/Japan)',
  'Q156 Geographic Area Far East (China/Japan)',
  'Q11 Public Engagement Audience Festival audience',
  'Q106 Materials Func. Ceramics and Inorganics',
  'Q107 Materials Func. Organics and Polymers',
  'Q26 Public Engagement Methodology Game or play activity',
  'Q77 Use of Facilities Gas Electron Diffraction Serv.',
  'Q173 Project Engagement by Sector General Public',
  'Q219 Health categories Generic Health Relevance',
  'QP7  Geographic Area',
  'Q15 Public Engagement Audience Government/policy-makers',
  'QP11  Health categories',
  'Q125 Time Period Hellenist-Sassanid:300BC-AD651',
  'Q128 Time Period Hellenistic Greek World: c.323',
  'Q122 Time Period Hellenistic&Roman: 300BC-700AD',
  'Q49 Use of Facilities High power lasers',
  'Q51 Use of Facilities ILL',
  'Q48 Use of Facilities ISIS',
  'Q231 Geographic Area Indian Ocean',
  'Q206 Health categories Infection',
  'Q207 Health categories Inflammatory and Immune System',
  'Q208 Health categories Injuries and Accidents',
  'Q162 Approach International Comparative',
  'Q70 Use of Facilities Ion Beam Facility',
  'Q142 Geographic Area Ireland',
  'Q183 Collaboration location region Ireland',
  'Q171 Approach Knowledge exchange',
  'Q168 Approach Large new datasets',
  'Q55 Use of Facilities Laser Loan Pool',
  'Q52 Use of Facilities Lasers for Science',
  'Q131 Time Period Later Roman Empire: AD250-450',
  'Q28 Public Engagement Methodology Lecture',
  'Q167 Approach Longitudinal Studies',
  'Q108 Materials Magnetic Materials',
  'Q59 Use of Facilities Mass Spectrometry Service',
  'Q34 Public Engagement Methodology Mass media',
  'QP5 Materials',
  'Q116 Materials Materials for nuclear power',
  'Q134 Time Period Medieval: c.1000 - 1500',
  'Q189 Collaboration location region Mediterranean',
  'Q148 Geographic Area Mediterranean',
  'Q209 Health categories Mental Health',
  'Q210 Health categories Metabolic and Endocrine',
  'Q109 Materials Metals & Alloys',
  'Q194 Collaboration location region Middle East',
  'Q153 Geographic Area Middle East',
  'Q164 Approach Modelling',
  'Q74 Use of Facilities Multiscale X-Ray Imaging',
  'Q211 Health categories Musculoskeletal',
  'Q12 Public Engagement Audience Museum audience',
  'Q64 Use of Facilities NCESS',
  'Q19 Public Engagement Audience NGP/campaigners',
  'Q176 Project Engagement by Sector NHS Health Prof & Social Serv',
  'Q63 Use of Facilities Nat.Serv. Comp. Chem. Software',
  'Q57 Use of Facilities National Grid Service (NGS)',
  'Q118 Time Period Neolithic, Copper and Bronze',
  'Q212 Health categories Neurological',
  'Q150 Geographic Area North America',
  'Q191 Collaboration location region North America',
  'Q196 Collaboration location region Oceania',
  'Q155 Geographic Area Oceania',
  'Q37 Public Engagement Methodology Open days',
  'Q41 Public Engagement Methodology Opinion Poll',
  'Q213 Health categories Oral and Gastrointestinal',
  'Q222 Health categories Other',
  'Q46 Public Engagement Methodology Other',
  'Q20 Public Engagement Audience Other',
  'Q54 Use of Facilities Other Neutrons',
  'Q181 Project Engagement by Sector Other Public Sector',
  'Q53 Use of Facilities Other Synchrotron',
  'Q232 Geographic Area Pacific Ocean',
  'Q117 Time Period Palaeolithic and Mesolithic',
  'Q6 Public Engagement Audience Parents',
  'Q115 Materials Photonic materials',
  'Q223 Geographic Area Polar',
  'Q161 Approach Practice Based',
  'Q178 Project Engagement by Sector Press and Media',
  'Q3 Public Engagement Audience Primary and secondary schools',
  'Q1 Public Engagement Audience Primary schools',
  'Q179 Project Engagement by Sector Professional/Statutory Bodies',
  'QP9  Project Engagement by Sector',
  'Q119 Time Period Protohistory and Iron Age',
  'QP1  Public Engagement Audience',
  'QP2  Public Engagement Methodology',
  'Q21 Public Engagement Methodology Public dialogue (deliberative)',
  'Q22 Public Engagement Methodology Public dialogue discuss/debate',
  'Q30 Public Engagement Methodology Public display/installation',
  'Q36 Public Engagement Methodology Publication',
  'Q159 Approach Qualitative',
  'Q160 Approach Quantitative',
  'Q136 Time Period Renaissance',
  'Q214 Health categories Renal and Urogenital',
  'Q215 Health categories Reproduct. Health & Childbirth',
  'Q216 Health categories Respiratory',
  'Q10 Public Engagement Audience Retired people',
  'Q130 Time Period Roman Empire: c.31BC-AD250',
  'Q129 Time Period Roman Republic: c. 400-31BC',
  'Q198 Collaboration location region Russia and Central Asia',
  'Q157 Geographic Area Russia and Central Asia',
  'Q158 Geographic Area S Asia (Pakistan to Indonesia)',
  'Q199 Collaboration location region S Asia (Pakistan to Indonesia)',
  'Q149 Geographic Area Scandinavia',
  'Q190 Collaboration location region Scandinavia',
  'Q33 Public Engagement Methodology School resource/curriculum',
  'Q16 Public Engagement Audience Scientists/engineers/academia',
  'Q144 Geographic Area Scotland',
  'Q185 Collaboration location region Scotland',
  'Q2 Public Engagement Audience Secondary schools',
  'Q110 Materials Semiconductor Materials',
  'Q217 Health categories Skin',
  'Q38 Public Engagement Methodology Social networking',
  'Q67 Use of Facilities Solid State NMR Service',
  'Q151 Geographic Area South America',
  'Q192 Collaboration location region South America',
  'Q233 Geographic Area Southern Ocean',
  'Q23 Public Engagement Methodology Spontaneous interact/discuss',
  'Q13 Public Engagement Audience Street audience/passers-by',
  'Q218 Health categories Stroke',
  'Q111 Materials Structural Polymers',
  'Q113 Materials Structural ceramics/inorganics',
  'Q174 Project Engagement by Sector Student Teachers & Undergrads',
  'Q124 Time Period Sumerian-Persian: 3500-300BC',
  'Q112 Materials Superconductors',
  'Q79 Theoretical Methods T&M Car-Parrinello Methods',
  'Q80 Theoretical Methods T&M Charge Density',
  'Q83 Theoretical Methods T&M Comp. Aided Design (CAD)',
  'Q82 Theoretical Methods T&M Comp. Fluid Dynamics',
  'Q81 Theoretical Methods T&M Computational Chemistry',
  'Q84 Theoretical Methods T&M Correlation Analysis',
  'Q85 Theoretical Methods T&M Density Functional Theory',
  'Q86 Theoretical Methods T&M Finite Element Methods',
  'Q87 Theoretical Methods T&M Modelling',
  'Q88 Theoretical Methods T&M Molecular Dynamics',
  'Q89 Theoretical Methods T&M Monte Carlo',
  "Q90 Theoretical Methods T&M Nonlin. Differential Equ'n",
  'Q91 Theoretical Methods T&M Numerical Analysis',
  'Q92 Theoretical Methods T&M Probabilistic Modelling',
  'Q93 Theoretical Methods T&M QSAR',
  'Q94 Theoretical Methods T&M Quantum Dynamics',
  'Q95 Theoretical Methods T&M Quantum Mechanics',
  'Q96 Theoretical Methods T&M Quantum Theory',
  'Q97 Theoretical Methods T&M Semi-empirical Methods',
  'Q98 Theoretical Methods T&M Simulation',
  'Q99 Theoretical Methods T&M Statistical Mechanics',
  'Q100 Theoretical Methods T&M Stochastic Modelling',
  'Q101 Theoretical Methods T&M Time Dependent Stat. Mech.',
  'Q102 Theoretical Methods T&M Total Energy Calculations',
  'Q103 Theoretical Methods T&M Visualisation',
  'Q78 Theoretical Methods T&M ab initio approaches',
  'Q44 Public Engagement Methodology Teacher development',
  'Q5 Public Engagement Audience Teachers',
  'Q166 Approach Technique/Method Development',
  'Q121 Time Period The Pharaonic: c.3000 - 300BC',
  'Q32 Public Engagement Methodology Theatre/drama/performance',
  'QP4  Theoretical Methods',
  'Q163 Approach Theory Development',
  'Q175 Project Engagement by Sector Third Sector',
  'Q18 Public Engagement Audience Those affected by issue',
  'QP6  Time Period',
  'Q35 Public Engagement Methodology Training for researchers',
  'Q170 Approach Training oriented',
  'Q76 Use of Facilities UH Magnetic Field Facility',
  'Q182 Collaboration location region UK & Ireland',
  'Q141 Geographic Area UK & Ireland',
  'Q14 Public Engagement Audience Unusual venue audience',
  'QP3 Use of Facilities',
  'Q45 Public Engagement Methodology Visit by school to laboratory',
  'Q186 Collaboration location region Wales',
  'Q145 Geographic Area Wales',
  'Q75 Use of Facilities Wave Testing Facility',
  'Q31 Public Engagement Methodology Website dominated activity',
  'Q146 Geographic Area Western Europe',
  'Q187 Collaboration location region Western Europe',
  'Q25 Public Engagement Methodology Workshop',
  'Q62 Use of Facilities X-Ray Crystallography Service',
  'Q71 Use of Facilities X-Ray Magn. Scattering (XMaS)',
  'Q73 Use of Facilities XUV-CMR',
  'Q4 Public Engagement Audience Young people (outside school)',
];
export const allQualifiers = qualifiers;
