let taxonomyList = [
  'Agricultural systems',
  'Crop protection',
  'Crop science',
  'Earth & environmental',
  'Soil science',
  '3Rs',
  'Animal & human physiology',
  'Animal behaviour',
  'Animal diseases',
  'Animal organisms',
  'Animal reproduction',
  'Animal welfare',
  'Endocrinology',
  'Immunology',
  'Livestock production',
  'Musculoskeletal system',
  'Parasitology',
  'Systems neuroscience',
  'Psychology',
  'Archaeological Theory',
  'Archaeology Of Human Origins',
  'Archaeology of Literate Soc.',
  'Landscape & Environ. Archaeol.',
  'Palaeobiology',
  'Prehistoric Archaeology',
  'Science-Based Archaeology',
  'Quaternary Science',
  'Maritime Archaeology',
  'Industrial Archaeology',
  'African Studies',
  'American Studies',
  'Hispanic & Latin American Stud',
  'Asian & Middle Eastern Studies',
  'European Studies',
  'Pacific Studies',
  'Oceanic Studies',
  'Astron. & Space Sci. Technol.',
  'Data Handling & Storage',
  'Extra-Galactic Astron.&Cosmol.',
  'Galactic & Interstellar Astron',
  'Part. Phys/Astron. Instrument.',
  'Stellar Astronomy',
  'Computational Methods & Tools',
  'Atmospheric Kinetics',
  'Boundary Layer Meteorology',
  'Large Scale Dynamics/Transport',
  'Radiative Processes & Effects',
  'Stratospheric Processes',
  'Tropospheric Processes',
  'Upper Atmos Process & Geospace',
  'Water In The Atmosphere',
  'Ocean - Atmosphere Interact.',
  'Land - Atmosphere Interactions',
  'Atoms & Ions',
  'Cold Atomic Species',
  'Light-Matter Interactions',
  'Scattering & Spectroscopy',
  'Fusion',
  'Biochemical engineering',
  'Bionanoscience',
  'Bioreactors',
  'Environmental biotechnology',
  'Macro-molecular delivery',
  'Metabolic engineering',
  'Novel industrial products',
  'Protein engineering',
  'Tissue engineering',
  'Bioenergy',
  'Biomaterials',
  'Biochemistry & physiology',
  'Bioenergetics',
  'Biological membranes',
  'Carbohydrate Chemistry',
  'Catalysis & enzymology',
  'Chemical Biology',
  'Multiprotein complexes',
  'Protein chemistry',
  'Protein expression',
  'Protein folding / misfolding',
  'Structural biology',
  'Ageing: chemistry/biochemistry',
  'Biophysics',
  'Catalysis & Applied Catalysis',
  'Electrochemical Science & Eng.',
  'Surfaces & Interfaces',
  'Complex fluids & soft solids',
  'Cell cycle',
  'Cells',
  'Communication & signalling',
  'Organelles & components',
  'Receptors',
  'Stem cell biology',
  'Gas & Solution Phase Reactions',
  'Physical Organic Chemistry',
  'Analytical Science',
  'Chemical Structure',
  'Instrumentation Eng. & Dev.',
  'Asymmetric Chemistry',
  'Biological & Medicinal Chem.',
  'Chemical Synthetic Methodology',
  'Combinatorial Chemistry',
  'Co-ordination Chemistry',
  'Synthetic biology',
  'Drug Formulation & Delivery',
  'Building Ops & Management',
  'Civil Engineering Materials',
  'Construction Ops & Management',
  'Ground Engineering',
  'Mining & Minerals Extraction',
  'Pavement Engineering',
  'Structural Engineering',
  'Transport Ops & Management',
  'Urban & Land Management',
  'Water Engineering',
  'Coastal & Waterway Engineering',
  'Waste Management',
  'Earth Engineering',
  'Materials testing & eng.',
  'Oil & Gas Extraction',
  'Classical Literature',
  'Classical Reception',
  'Languages & Linguistics',
  'Epigraphy & Papyrology',
  'Philosophy, Thought & Religion',
  'Climate & Climate Change',
  'Regional & Extreme Weather',
  'Palaeoenvironments',
  'Complexity Science',
  'Conservation Of Art & Textiles',
  'Conservation Science',
  'Cultural Geography',
  'Cultural Studies & Pop Culture',
  'Gender & Sexuality Studies',
  'Heritage Management',
  'Museum & Gallery Studies',
  'Policy, Arts Mgmt & Creat Ind',
  'Choreography',
  'Dance Notation',
  'Dance Performance',
  'History Of Dance',
  'Social Dance',
  'Demography (General)',
  'Reproductive and sexual health',
  'Demography',
  'Human Geography',
  'Architecture HTP',
  'Design Engineering',
  'Design Processes',
  'Digital Art & Design',
  'Product Design',
  'Design HTP',
  'Area & Development Studies',
  'Pol.,International Rel.&Dev.',
  'Economic Development',
  'Development Studies',
  'Sociology and Development',
  'Nat Resources, Env & Rural Dev',
  'Anthropology and Development',
  'Social policy and Development',
  'Global Health and Medicine',
  'Internat Education and Dev',
  'Law, Democracy and Development',
  'Demography and Development',
  'Dev Informatics & Technology',
  'Geography and Development',
  'Management & Bus Studies & Dev',
  'Regional Development',
  'Drama & Theatre - Other',
  'Dramaturgy',
  'Performance & Live Art',
  'Scenography',
  'Theatre & History',
  'Theatre & Society',
  'Theories Of Theatre',
  'Behavioural Ecology',
  'Community Ecology',
  'Conservation Ecology',
  'Population Ecology',
  'Systematics & Taxonomy',
  'Economics (General)',
  'Development economics',
  'Econometrics',
  'Financial economics',
  'Industrial Organisation (R&D)',
  'International economics',
  'Macroeconomics',
  'Labour economics',
  'Public economics',
  'Microeconomic theory',
  'Law and economics',
  'Behavioural & experimental eco',
  'Environmental economics',
  'Education (General)',
  'Sociology of Education',
  'Psychology of Education',
  'Curriculum areas',
  'Elements of Education',
  'Phases of education',
  'Education Policy',
  'ICT and education',
  'Bioelectronic Devices',
  'Electric Motor & Drive Systems',
  'Power Electronics',
  'Power Sys Man, Prot & Control',
  'Power Systems Plant',
  'Robotics & Autonomy',
  'Optical Devices & Subsystems',
  'Optoelect. Devices & Circuits',
  'Carbon Capture & Storage',
  'Coal Technology',
  'Energy - Conventional',
  'Energy - Marine & Hydropower',
  'Energy - Nuclear',
  'Energy Efficiency',
  'Energy Storage',
  'Fuel Cell Technologies',
  'Solar Technology',
  'Sustainable Energy Networks',
  'Sustainable Energy Vectors',
  'Wind Power',
  'Assess/Remediate Contamination',
  'Waste Minimisation',
  'Env Planning (General)',
  'Spatial Planning',
  'Urban Design',
  'Landscape  Architecture',
  'Accelerator R&D',
  'Central Laser Facility',
  'Diamond Light Source',
  'ESRF',
  'ILL',
  'ISIS T1',
  'ISIS T2',
  'Research complex at Harwell',
  'X-FEL',
  'Diet & health',
  'Food microbiology',
  'Food processing',
  'Food structure/composition',
  'Animal developmental biology',
  'Epigenetics',
  'Evolution & populations',
  'Gene action & regulation',
  'Gene therapy',
  'Genome organisation',
  'Microbial',
  'Population Genetics/Evolution',
  'Recombination',
  'Geohazards',
  'Glacial & Cryospheric Systems',
  'Hydrogeology',
  'Hydrological Processes',
  'Mantle & Core Processes',
  'Properties Of Earth Materials',
  'Sediment/Sedimentary Processes',
  'Tectonic Processes',
  'Volcanic Processes',
  'Earth Resources',
  'Cultural History',
  'Economic & Soc Hist (General)',
  'History of Sci./Med./Technol.',
  'Imperial/Colonial History',
  'Industrial History',
  'Maritime History',
  'Political History',
  'Post-Colonial Studies',
  'Religious History',
  'War Studies',
  'Human Geography (General)',
  'Demography/Pop Geography',
  'Cultural and Anthrop Geography',
  'Social Geography',
  'Economic Geography',
  'Political Geography',
  'Historical Geography',
  'Environmental Geography',
  'Development Geography',
  'Urban Geography',
  'Rural Geography',
  'Recreation/Tourism Geography',
  'Transport Geography',
  'Regional Geography',
  'Cartography and GIS',
  'Artificial Intelligence',
  'Cognitive Science Appl. in ICT',
  'Computer Graphics & Visual.',
  'Digital Signal Processing',
  'Displays',
  'Electronic Devices & Subsys.',
  'Fundamentals of Computing',
  'Human Communication in ICT',
  'Human-Computer Interactions',
  'Networks & Distributed Systems',
  'Image & Vision Computing',
  'Information & Knowledge Mgmt',
  'Microsystems',
  'Mobile Computing',
  'Modelling & simul. of IT sys.',
  'Multimedia',
  'Music & Acoustic Technology',
  'New & Emerging Comp. Paradigms',
  'Optical Communications',
  'Parallel Computing',
  'RF & Microwave Technology',
  'Software Engineering',
  'System on Chip',
  'Vision & Senses - ICT appl.',
  'VLSI Design',
  'Computer Sys. & Architecture',
  'Exploration Technology',
  'Survey & Monitoring',
  'Middle East & African Studies',
  'Asiatic & Oriental Studies',
  'Australasian Studies',
  'Celtic Studies',
  'Comparative Literature',
  'Comparative Studies',
  'Creative Writing',
  'English Language & Literature',
  'Ethnography & Anthropology',
  'French Studies',
  'German, inc. Dutch & Yiddish',
  'Hispanic, Portguese & Latin',
  'History & Dev. of English Lang',
  'Interpreting & Translation',
  'Italian Studies',
  'Language Training/Educational',
  'Lifewriting',
  'Literary & Cultural Theory',
  'Medieval Literature',
  'Russian, Slavonic & E European',
  'Scandinavian Studies',
  'Gender & Sexuality',
  'Common Law inc. Commercial Law',
  'Comparative Law',
  'Criminal Law & Criminology',
  'EU Law',
  'Human Rights',
  'International Law',
  'Jurisprudence/Legal Philosophy',
  'Law Regulated By Statute',
  'Law Relating To Property',
  'Legal History',
  'Public Law',
  'Socio Legal Studies',
  'Archives',
  'Computational Studies',
  'Information Sci. & Retrieval',
  'Library Studies',
  'Records Management',
  'Language Acquisition',
  'Language Variation & Change',
  'Applied Linguistics',
  'Comput/Corpus Linguistics',
  'Lexicon',
  'Linguistic Theory',
  'Morphology & Phonology',
  'Phonetics',
  'Psycholinguistics',
  'Semantics & Pragmatics',
  'Sociolinguistics',
  'Syntax',
  'Textual Editing & Bibliography',
  'Linguistics (General)',
  'Computational Linguistics',
  'Corpus Linguistics',
  'Manage & Bus Stud (General)',
  'Manufact. Business Strategy',
  'Manufact. Enterprise Ops& Mgmt',
  'Strategic Management',
  'Project Studies',
  'Entrepreneurship',
  'Leadership',
  'Employment Studies',
  'Human Resource Management',
  'Innovation',
  'Marketing',
  'Operations Management',
  'Hosp, Leisure & tourism manage',
  'Governance',
  'Sustainability Management',
  'Knowledge Management',
  'Retail Management',
  'Public Administration',
  'Organisational Studies',
  'International Business',
  'Finance and Accounting',
  'Manufacturing Machine & Plant',
  'Design & Testing Technology',
  'Ecosystem Scale Processes',
  'Land - Ocean Interactions',
  'Ocean Circulation',
  'Biogeochemical Cycles',
  'Materials Processing',
  'Particle Technology',
  'Materials Characterisation',
  'Materials Synthesis & Growth',
  'Algebra & Geometry',
  'Continuum Mechanics',
  'Logic & Combinatorics',
  'Mathematical Analysis',
  'Mathematical Aspects of OR',
  'Mathematical Physics',
  'Non-linear Systems Mathematics',
  'Numerical Analysis',
  'Statistics & Appl. Probability',
  'Acoustics',
  'Aerodynamics',
  'Combustion',
  'Eng. Dynamics & Tribology',
  'Mech. & Fluid Power Transmiss.',
  'Underwater Engineering',
  'Heat & Mass Transfer',
  'Journalism',
  'Media & Communication Studies',
  'New Media/Web-Based Studies',
  'Publishing',
  'Television HTC',
  'Film History, T & C',
  'Biomechanics & Rehabilitation',
  'Biomedical neuroscience',
  'Biomedical sciences',
  'Environment & Health',
  'Med.Instrument.Device& Equip.',
  'Medical science & disease',
  'Mental Health',
  'Tissue Engineering',
  'Extremophiles',
  'Microbiology',
  'Microorganisms',
  'Responses to environment',
  'Environmental Microbiology',
  'Classical Music',
  'Composition',
  'History Of Music',
  'Music & Society',
  'Musical Performance',
  'Musicology',
  'Popular Music',
  'Traditional Music',
  'Hadron Physics',
  'Nuclear Astrophysics',
  'Nuclear Structure',
  'Relativistic Heavy Ions',
  'Environmental Genomics',
  'Functional genomics',
  'Genomics',
  'Glycomics',
  'Metabolomics / Metabonomics',
  'Proteomics',
  'Transcriptomics',
  'Lasers & Optics',
  'Optical Phenomena',
  'Quantum Optics & Information',
  'Cosmic Microwave Background',
  'Cosmology',
  'Direct Dark Matter Detection',
  'Gamma Ray Astronomy',
  'Gravitational Waves',
  'High Energy Cosmic Rays',
  'B Physics/Flavour Physics',
  'Beyond The Standard Model',
  'Dark Energy',
  'Neutrino Physics',
  'Lattice QCD',
  'Phenomenology',
  'Quantum Field Theory',
  'String Theory',
  'The Standard Model',
  'Aesthetics',
  'Epistemology',
  'Ethics',
  'History Of Ideas',
  'History Of Philosophy',
  'Language & Philosophical Logic',
  'Metaphysics',
  'Philosophy Of Mind',
  'Philosophy Of Religion',
  'Science & Maths, & Math Logic',
  'Political Philosophy',
  'Extra Solar Planets',
  'Non-Terrestrial Planetary Sci.',
  'Planetary Atmospheres',
  'Planetary Surfaces & Geology',
  'Solar Bodies',
  'Environmental Physiology',
  'Interaction with organisms',
  'Plant cell biology',
  'Plant developmental biology',
  'Plant organisms',
  'Plant physiology',
  'Plant reproductive biology',
  'Plant responses to environment',
  'Plasmas - Laser & Fusion',
  'Plasmas - Technological',
  'Diplomacy & Internat Relations',
  'Internat. Studies & Relations',
  'Political Science',
  'Politics',
  'International Organisations',
  'International Relations Theory',
  'Peace Studies',
  'Conflict/War Studies',
  'Security Studies',
  'Internat Political Economy',
  'Foreign Policy Studies',
  'Elections/Electoral studies',
  'Middle East Studies',
  'European/EU Studies',
  'Ecotoxicology',
  'Pollution',
  'Bioprocess Engineering',
  'Design of Process systems',
  'Fluid Dynamics',
  'Multiphase Flow',
  'Reactor Engineering',
  'Rheology',
  'Safety & Reliability of Plant',
  'Separation Processes',
  'Psychology (General)',
  'Biological Psychology',
  'Child Psychology',
  'Cognitive Psychology',
  'Developmental Psychology',
  'Education and School',
  'Experimental Psychology',
  'Forensic Psychology',
  'Health Psychology',
  'Industrial-Org/Occupational',
  'Social Psychology',
  'Sport and Exercise',
  'Mathematical & Statistic Psych',
  'Gerontology',
  'Science & Technology Studies',
  'Science and Technology Studies',
  'Social Anthropology (General)',
  'Econ, Pol & Env Anthropology',
  'Kinship Health & relatedness',
  'Rel, Material & Cog Anthrop',
  'Anthropological Methodology',
  'Social Policy (General)',
  'Social Work (General)',
  'Children and Families',
  'Social Work with Adults',
  'International Social Work',
  'Sociology (General)',
  'Criminology',
  'Cultural Studies',
  'Economic Sociology',
  'Edu Sociocloy/Sociology of Edu',
  'Ethnicity',
  'Environment',
  'Globalism and Development',
  'Media Studies',
  'Med Soc/Soc Health & Illness',
  'Political Sociology',
  'Sociology of Religion',
  'Social Theory',
  'Stratification',
  'Urbanisation',
  'Womens and Gender Studies',
  'Solar & Solar-Terrestrial Phys',
  'Solar Studies',
  'Condensed Matter Physics',
  'Electromagnetics',
  'Magnetism/Magnetic Phenomena',
  'Quantum Fluids & Solids',
  'Control Engineering',
  'Intelligent & Expert Systems',
  'Intelligent Measurement Sys.',
  'Earth Surface Processes',
  'Water Quality',
  'Alternative Spiritualities',
  'Atheism/Secularism',
  'Buddhism',
  'History of Church & Theology',
  'Contemporary Religion',
  'East Asian Religions',
  'Hinduism',
  'Inter-faith Relations',
  'Islam',
  'Jainism',
  'Judaism',
  'Liturgy',
  'Modern Theology',
  'New Testament',
  'Old Testament',
  'Sikhism',
  'Systematic Theology',
  'Bioinformatics',
  'Bionanotechnology',
  'Development (Biosciences)',
  'Environmental Informatics',
  'eScience',
  'High Performance Computing',
  'Medical Imaging',
  'Research approaches',
  'Social Stats., Comp. & Methods',
  'Technol. for Environ. Appl.',
  'Theoretical biology',
  'Tools for the biosciences',
  'Remote Sensing & Earth Obs.',
  'Technology and method dev',
  'Applied Arts HTP',
  'Art History',
  'Art Theory & Aesthetics',
  'Digital Arts HTP',
  'Fine Art HTP',
  'Installation & Sound Art HTP',
  'Photography HTP',
  'Time-Based Media HTP',
  'Film-based media (H, T & P)',
  'Community Art inc A & H',
];
