const allTeamMembersFull = [
  {
    id: '1',
    firstName: 'Manolo',
    lastName: 'Bauer',
    role: '',
    roleType: 'Directly allocated',
    organisation: 'University of Wales',
    email: 'manolo.bauer@wales.ac.uk',
    timeSpent: '',
    averageHours: '',
    isComplete: true,
  },
  {
    id: '2',
    firstName: 'Tina',
    lastName: 'Smollins',
    role: '',
    roleType: 'Directly allocated',
    organisation: 'University of Bristol',
    email: 'tina.smollins@bristol.ac.uk',
    timeSpent: '',
    averageHours: '',
    isComplete: true,
  },
  {
    id: '3',
    firstName: 'Bingo',
    lastName: 'Smithers',
    role: 'Researcher',
    roleType: 'Exception',
    organisation: 'University of Bristol',
    email: 'bingo.smithers@bristol.ac.uk',
    timeSpent: '75',
    averageHours: '40',
    startDay: '12',
    startMonth: '1',
    startYear: '2023',
    endDay: '1',
    endMonth: '1',
    endYear: '2024',
    isComplete: true,
  },
  {
    id: '4',
    firstName: 'Wallace',
    lastName: 'Trumpton',
    role: 'Technician',
    roleType: 'Directly incurred',
    organisation: 'University of Wales',
    email: 'bingo.smithers@wales.ac.uk',
    timeSpent: '100',
    averageHours: '40',
    startDay: '12',
    startMonth: '1',
    startYear: '2023',
    endDay: '12',
    endMonth: '1',
    endYear: '2024',
    isComplete: true,
  },
  {
    id: '5',
    firstName: '',
    lastName: '',
    role: '',
    roleType: '',
    organisation: '',
    email: '',
    timeSpent: '',
    averageHours: '',
    startDay: '',
    startMonth: '',
    startYear: '',
    endDay: '',
    endMonth: '',
    endYear: '',
    isComplete: false,
  },
  {
    id: '6',
    firstName: '',
    lastName: '',
    role: '',
    roleType: '',
    organisation: '',
    email: '',
    timeSpent: '',
    averageHours: '',
    startDay: '',
    startMonth: '',
    startYear: '',
    endDay: '',
    endMonth: '',
    endYear: '',
    isComplete: false,
  },
  {
    id: '7',
    firstName: '',
    lastName: '',
    role: '',
    roleType: '',
    organisation: '',
    email: '',
    timeSpent: '',
    averageHours: '',
    startDay: '',
    startMonth: '',
    startYear: '',
    endDay: '',
    endMonth: '',
    endYear: '',
    isComplete: false,
  },
  {
    id: '8',
    firstName: '',
    lastName: '',
    role: '',
    roleType: '',
    organisation: '',
    email: '',
    timeSpent: '',
    averageHours: '',
    startDay: '',
    startMonth: '',
    startYear: '',
    endDay: '',
    endMonth: '',
    endYear: '',
    isComplete: false,
  },
  {
    id: '9',
    firstName: '',
    lastName: '',
    role: '',
    roleType: '',
    organisation: '',
    email: '',
    timeSpent: '',
    averageHours: '',
    startDay: '',
    startMonth: '',
    startYear: '',
    endDay: '',
    endMonth: '',
    endYear: '',
    isComplete: false,
  },
  {
    id: '10',
    firstName: '',
    lastName: '',
    role: '',
    roleType: '',
    organisation: '',
    email: '',
    timeSpent: '',
    averageHours: '',
    startDay: '',
    startMonth: '',
    startYear: '',
    endDay: '',
    endMonth: '',
    endYear: '',
    isComplete: false,
  },
];

export const teamDataFull = allTeamMembersFull;

const allTeamMembersEmpty = [
  {
    id: '1',
    firstName: 'Manolo',
    lastName: 'Bauer',
    role: '',
    roleType: 'Directly allocated',
    organisation: 'University of Wales',
    email: 'manolo.bauer@wales.ac.uk',
    timeSpent: '',
    averageHours: '',
    isComplete: true,
  },
  {
    id: '2',
    firstName: '',
    lastName: '',
    role: '',
    roleType: '',
    organisation: '',
    email: '',
    timeSpent: '',
    averageHours: '',
    startDay: '',
    startMonth: '',
    startYear: '',
    endDay: '',
    endMonth: '',
    endYear: '',
    isComplete: false,
  },
  {
    id: '3',
    firstName: '',
    lastName: '',
    role: '',
    roleType: '',
    organisation: '',
    email: '',
    timeSpent: '',
    averageHours: '',
    startDay: '',
    startMonth: '',
    startYear: '',
    endDay: '',
    endMonth: '',
    endYear: '',
    isComplete: false,
  },
  {
    id: '4',
    firstName: '',
    lastName: '',
    role: '',
    roleType: '',
    organisation: '',
    email: '',
    timeSpent: '',
    averageHours: '',
    startDay: '',
    startMonth: '',
    startYear: '',
    endDay: '',
    endMonth: '',
    endYear: '',
    isComplete: true,
  },
  {
    id: '5',
    firstName: '',
    lastName: '',
    role: '',
    roleType: '',
    organisation: '',
    email: '',
    timeSpent: '',
    averageHours: '',
    startDay: '',
    startMonth: '',
    startYear: '',
    endDay: '',
    endMonth: '',
    endYear: '',
    isComplete: false,
  },
  {
    id: '6',
    firstName: '',
    lastName: '',
    role: '',
    roleType: '',
    organisation: '',
    email: '',
    timeSpent: '',
    averageHours: '',
    startDay: '',
    startMonth: '',
    startYear: '',
    endDay: '',
    endMonth: '',
    endYear: '',
    isComplete: false,
  },
  {
    id: '7',
    firstName: '',
    lastName: '',
    role: '',
    roleType: '',
    organisation: '',
    email: '',
    timeSpent: '',
    averageHours: '',
    startDay: '',
    startMonth: '',
    startYear: '',
    endDay: '',
    endMonth: '',
    endYear: '',
    isComplete: false,
  },
  {
    id: '8',
    firstName: '',
    lastName: '',
    role: '',
    roleType: '',
    organisation: '',
    email: '',
    timeSpent: '',
    averageHours: '',
    startDay: '',
    startMonth: '',
    startYear: '',
    endDay: '',
    endMonth: '',
    endYear: '',
    isComplete: false,
  },
  {
    id: '9',
    firstName: '',
    lastName: '',
    role: '',
    roleType: '',
    organisation: '',
    email: '',
    timeSpent: '',
    averageHours: '',
    startDay: '',
    startMonth: '',
    startYear: '',
    endDay: '',
    endMonth: '',
    endYear: '',
    isComplete: false,
  },
  {
    id: '10',
    firstName: '',
    lastName: '',
    role: '',
    roleType: '',
    organisation: '',
    email: '',
    timeSpent: '',
    averageHours: '',
    startDay: '',
    startMonth: '',
    startYear: '',
    endDay: '',
    endMonth: '',
    endYear: '',
    isComplete: false,
  },
];

export const teamDataEmpty = allTeamMembersEmpty;
